from typing import Dict, List, Any

BOSS_EXCLUSIVE_DROPS = {
    "golem": [
        {
            "name": "Гранитный Молот Сокрушения",
            "icon": "🔨",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "rare",
            "rarity_name": "Редкий",
            "rarity_color": "#3b82f6",
            "base_min": 34,
            "base_max": 48,
            "bonus": {"stun_chance": 12, "str": 8},
            "bonus_desc": "⚔️ +34..48 Урон | 💥 +12% Шанс оглушения | 🥩 +8 Сила"
        },
        {
            "name": "Осколок Гранитного Кристалла",
            "icon": "🔮",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "rare",
            "rarity_name": "Редкий",
            "rarity_color": "#3b82f6",
            "bonus": {"int": 10, "spell_amp": 8, "magic_dmg": 14},
            "bonus_desc": "🔮 +10 Интеллект | ✨ +8% Сила заклинаний | ⚡ +14 Магический урон"
        },
        {
            "name": "Обсидиановый Доспех Колосса",
            "icon": "🛡️",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "rare",
            "rarity_name": "Редкий",
            "rarity_color": "#3b82f6",
            "defense": 14,
            "hp_bonus": 90,
            "bonus": {"damage_block": 12, "hp": 90},
            "bonus_desc": "🛡️ +14 Броня | ❤️ +90 HP | 🧱 Блок 12 ед. урона"
        },
        {
            "name": "Кинжал из Обсидиана",
            "icon": "🗡️",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "rare",
            "rarity_name": "Редкий",
            "rarity_color": "#3b82f6",
            "base_min": 30,
            "base_max": 44,
            "bonus": {"agi": 10, "atk_speed": 12, "crit": 8},
            "bonus_desc": "⚔️ +30..44 Урон | 🏃 +10 Ловкость | ⚡ +12% Скор. атаки | 💥 +8% Крит"
        }
    ],
    "lich": [
        {
            "name": "Ледяная Корона Архилича",
            "icon": "👑",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "epic",
            "rarity_name": "Эпический",
            "rarity_color": "#c084fc",
            "bonus": {"int": 20, "spell_amp": 15, "freeze_chance": 18},
            "bonus_desc": "🔮 +20 Интеллект | ✨ +15% Сила заклинаний | ❄️ 18% Шанс заморозки"
        },
        {
            "name": "Ледяное Око Архилича (Eye of Lich)",
            "icon": "❄️",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "epic",
            "rarity_name": "Эпический",
            "rarity_color": "#c084fc",
            "bonus": {"all_stats": 14, "slow_enemy": 20, "hp": 150, "mp": 150},
            "bonus_desc": "👑 +14 Все характеристики | ❄️ Замедление врагов 20% | ❤️ +150 HP | 🔮 +150 MP"
        },
        {
            "name": "Мантия Замерзшей Бездны",
            "icon": "🧥",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "epic",
            "rarity_name": "Эпический",
            "rarity_color": "#c084fc",
            "defense": 18,
            "hp_bonus": 130,
            "bonus": {"frost_armor": 18, "int": 14},
            "bonus_desc": "🛡️ +18 Броня | ❤️ +130 HP | ❄️ Ледяной панцирь замедляет атакующих"
        },
        {
            "name": "Посох Абсолютного Нуля",
            "icon": "🪄",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "epic",
            "rarity_name": "Эпический",
            "rarity_color": "#c084fc",
            "base_min": 48,
            "base_max": 72,
            "bonus": {"int": 18, "burst_magic": 80},
            "bonus_desc": "⚔️ +48..72 Урон | 🔮 +18 Интеллект | ⚡ Ледяной взрыв 80 ед."
        }
    ],
    "tormentor": [
        {
            "name": "Aghanim's Shard (Осколок Аганима)",
            "icon": "💎",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "epic",
            "rarity_name": "Эпический",
            "rarity_color": "#c084fc",
            "bonus": {"spell_amp": 18, "int": 16, "ult_boost": 20, "ult_cd": 12},
            "bonus_desc": "🔮 +16 Интеллект | ✨ +18% Сила заклинаний | 💥 +20% Урон Ульты | ⏱️ -12% КД"
        },
        {
            "name": "Отражающий Панцирь Терзателя",
            "icon": "🔮",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "epic",
            "rarity_name": "Эпический",
            "rarity_color": "#c084fc",
            "defense": 24,
            "hp_bonus": 160,
            "bonus": {"reflect": 25, "magic_resist": 15},
            "bonus_desc": "🛡️ +24 Броня | ❤️ +160 HP | 🪞 Отражает 25% входящего урона"
        },
        {
            "name": "Эфирный Фокус Терзателя",
            "icon": "🌀",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "epic",
            "rarity_name": "Эпический",
            "rarity_color": "#c084fc",
            "bonus": {"int": 18, "spell_amp": 16, "burst_magic": 120},
            "bonus_desc": "🔮 +18 Интеллект | ✨ +16% Сила заклинаний | ⚡ Эфирный разряд 120 ед."
        },
        {
            "name": "Кристальный Клинок Бездны",
            "icon": "🗡️",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "epic",
            "rarity_name": "Эпический",
            "rarity_color": "#c084fc",
            "base_min": 60,
            "base_max": 88,
            "bonus": {"crit": 18, "agi": 16},
            "bonus_desc": "⚔️ +60..88 Урон | 🏃 +16 Ловкость | 💥 +18% Крит"
        }
    ],
    "dragon": [
        {
            "name": "Чешуя Черного Дракона",
            "icon": "🌋",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "legendary",
            "rarity_name": "Легендарный",
            "rarity_color": "#f59e0b",
            "defense": 30,
            "hp_bonus": 240,
            "bonus": {"fire_aura": 35, "str": 20},
            "bonus_desc": "🛡️ +30 Броня | ❤️ +240 HP | 🔥 Огненная аура дракона 35/с"
        },
        {
            "name": "Огненный Клинок Бездны",
            "icon": "🔥",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "legendary",
            "rarity_name": "Легендарный",
            "rarity_color": "#f59e0b",
            "base_min": 95,
            "base_max": 135,
            "bonus": {"burn": 50, "crit": 25, "agi": 28},
            "bonus_desc": "⚔️ +95..135 Урон | 🏃 +28 Ловкость | 🔥 Поджигание | 💥 +25% Крит"
        },
        {
            "name": "Дыхание Инферно (Inferno Heart)",
            "icon": "☄️",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "legendary",
            "rarity_name": "Легендарный",
            "rarity_color": "#f59e0b",
            "bonus": {"int": 32, "spell_amp": 28, "meteor": 180},
            "bonus_desc": "🔮 +32 Интеллект | ✨ +28% Сила заклинаний | ☄️ Метеор 180 ед."
        }
    ],
    "pudge_boss": [
        {
            "name": "Окровавленный Крюк Мясника",
            "icon": "🪝",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "legendary",
            "rarity_name": "Легендарный",
            "rarity_color": "#f59e0b",
            "base_min": 115,
            "base_max": 160,
            "bonus": {"str": 30, "crit": 22, "lifesteal": 20},
            "bonus_desc": "⚔️ +115..160 Урон | 🥩 +30 Сила | 🩸 +20% Вампиризм | 💥 +22% Крит"
        },
        {
            "name": "Фартук Чумного Потрошителя",
            "icon": "🦺",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "legendary",
            "rarity_name": "Легендарный",
            "rarity_color": "#f59e0b",
            "defense": 36,
            "hp_bonus": 320,
            "bonus": {"damage_block": 35, "str": 25, "hp": 320},
            "bonus_desc": "🛡️ +36 Броня | ❤️ +320 HP | 🥩 +25 Сила | 🧱 Блок 35 урона"
        },
        {
            "name": "Гнилое Сердце Мясника",
            "icon": "🫀",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "legendary",
            "rarity_name": "Легендарный",
            "rarity_color": "#f59e0b",
            "bonus": {"str": 28, "rot_aura": 35, "hp": 280},
            "bonus_desc": "🥩 +28 Сила | ❤️ +280 HP | ☣️ Аура гниения 35/с"
        }
    ],
    "faceless_void": [
        {
            "name": "Булава Повелителя Времени",
            "icon": "🔨",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "legendary",
            "rarity_name": "Легендарный",
            "rarity_color": "#f59e0b",
            "base_min": 140,
            "base_max": 195,
            "bonus": {"agi": 32, "stun_chance": 25, "atk_speed": 30},
            "bonus_desc": "⚔️ +140..195 Урон | 🏃 +32 Ловкость | ⚡ +30% Скор. атаки | 💫 25% Таймлок"
        },
        {
            "name": "Панцирь Временного Разлома",
            "icon": "🛡️",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "legendary",
            "rarity_name": "Легендарный",
            "rarity_color": "#f59e0b",
            "defense": 40,
            "hp_bonus": 380,
            "bonus": {"dodge": 25, "hp": 380, "def": 40},
            "bonus_desc": "🛡️ +40 Броня | ❤️ +380 HP | 💨 +25% Уворот во времени"
        },
        {
            "name": "Хроно-Сфера Безвременья",
            "icon": "🔮",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "legendary",
            "rarity_name": "Легендарный",
            "rarity_color": "#f59e0b",
            "bonus": {"all_stats": 24, "cooldown_reduct": 18, "ult_cd": 20},
            "bonus_desc": "👑 +24 Все статы | ⏳ -18% КД всех способностей | ⏱️ -20% КД Ульты"
        }
    ],
    "roshan": [
        {
            "name": "Aegis of the Immortal",
            "icon": "🛡️",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"hp": 150, "def": 15, "revive": 1, "all_stats": 10},
            "bonus_desc": "👑 ВТОРАЯ ЖИЗНЬ: Воскрешение при гибели! | ❤️ +150 HP | 🛡️ +15 Броня"
        },
        {
            "name": "Divine Rapier (Рапира Богов)",
            "icon": "🗡️",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 180,
            "base_max": 260,
            "bonus": {"crit": 35, "pure_dmg": 30},
            "bonus_desc": "⚔️ +180..260 Урон | 💥 +35% Крит | 👑 Сила древних богов"
        },
        {
            "name": "Благословение Аганима (Aghanim Blessing)",
            "icon": "👑",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"all_stats": 30, "hp": 400, "mp": 400, "ult_boost": 45, "ult_cd": 20, "spell_amp": 15},
            "bonus_desc": "👑 +30 Все характеристики | 💥 +45% Урон Ульты | ⏱️ -20% КД Ульты | ✨ +15% Сила магии"
        },
        {
            "name": "Сердце Тарраска (Heart of Tarrasque)",
            "icon": "❤️",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 38,
            "hp_bonus": 650,
            "bonus": {"hp": 650, "str": 45, "regen": 40},
            "bonus_desc": "🛡️ +38 Броня | ❤️ +650 HP | 🥩 +45 Сила | 💖 +40 HP/сек Регенерация"
        },
        {
            "name": "Кираса Штурма (Assault Cuirass)",
            "icon": "🦺",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 45,
            "hp_bonus": 350,
            "bonus": {"atk_speed": 40, "def": 45, "armor_reduction": 15},
            "bonus_desc": "🛡️ +45 Броня | ⚡ +40% Скор. атаки | 🔨 Снижает броню врагов на 15"
        }
    ],
    "tidehunter": [
        {
            "name": "Титанический Якорь Кракена",
            "icon": "⚓",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 195,
            "base_max": 275,
            "bonus": {"str": 40, "stun_chance": 25, "weaken": 30},
            "bonus_desc": "⚔️ +195..275 Урон | 🥩 +40 Сила | 💥 25% Оглушение | 🌊 Снижает атаку врага на 30%"
        },
        {
            "name": "Панцирь Морского Левиафана",
            "icon": "🛡️",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 48,
            "hp_bonus": 450,
            "bonus": {"damage_block": 55, "hp": 450},
            "bonus_desc": "🛡️ +48 Броня | ❤️ +450 HP | 🌊 Чешуя Кракена: Блок 55 ед. любого урона"
        },
        {
            "name": "Жемчужина Океанической Бездны",
            "icon": "🔮",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"all_stats": 32, "water_surge": 300},
            "bonus_desc": "👑 +32 Все статы | 🌊 Волна глубин 300 ед. по площади"
        }
    ],
    "sf_boss": [
        {
            "name": "Дезолятор Тьмы (Desolator)",
            "icon": "🪓",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 210,
            "base_max": 290,
            "bonus": {"armor_pierce": 35, "crit": 30, "agi": 35},
            "bonus_desc": "⚔️ +210..290 Урон | 🩸 Пробивание брони 35 | 💥 +30% Крит"
        },
        {
            "name": "Пелерина Черного Реквиема",
            "icon": "👘",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 42,
            "hp_bonus": 400,
            "bonus": {"soul_steal": 20, "spell_amp": 25},
            "bonus_desc": "🛡️ +42 Броня | ❤️ +400 HP | 💀 Крадет души врагов при гибели"
        },
        {
            "name": "Венец Пожирателя Душ",
            "icon": "👑",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"agi": 35, "int": 35, "ult_boost": 50},
            "bonus_desc": "🏃 +35 Ловкость | 🔮 +35 Интеллект | 💥 +50% Урон Ульты"
        }
    ],
    "necrophos": [
        {
            "name": "Коса Жатвы Смерти (Reaper Scythe)",
            "icon": "⛏️",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 220,
            "base_max": 300,
            "bonus": {"execute_low_hp": 25, "int": 40},
            "bonus_desc": "⚔️ +220..300 Урон | 🔮 +40 Интеллект | ☠️ Казнь врагов ниже 25% HP"
        },
        {
            "name": "Октариновое Ядро (Octarine Core)",
            "icon": "🔮",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"cooldown_reduct": 25, "spell_lifesteal": 25, "hp": 450, "mp": 450},
            "bonus_desc": "⏱️ -25% КД всех способностей | 🩸 +25% Вампиризм заклинаниями"
        },
        {
            "name": "Саван Чумного Архимага",
            "icon": "🧥",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 46,
            "hp_bonus": 500,
            "bonus": {"rot_aura": 65, "int": 30},
            "bonus_desc": "🛡️ +46 Броня | ❤️ +500 HP | ☣️ Аура чумы выжигает 65 ед./сек вокруг"
        }
    ],
    "invoker_boss": [
        {
            "name": "Посох Арканы Владыки Стихий",
            "icon": "🪄",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 235,
            "base_max": 320,
            "bonus": {"spell_amp": 45, "int": 50, "meteor": 250},
            "bonus_desc": "⚔️ +235..320 Урон | 🔮 +50 Интеллект | ✨ +45% Сила магии | ☄️ Метеор 250"
        },
        {
            "name": "Мантия Высшего Демиурга",
            "icon": "🥻",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 48,
            "hp_bonus": 520,
            "bonus": {"all_stats": 35, "mp_regen": 30},
            "bonus_desc": "🛡️ +48 Броня | ❤️ +520 HP | 👑 +35 Все статы | 🔮 +30 MP/сек"
        },
        {
            "name": "Сфера Солнечного Удара (Sunstrike)",
            "icon": "☀️",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"pure_dmg": 85, "int": 45},
            "bonus_desc": "☀️ +85 Чистый урон ко всем атакам | 🔮 +45 Интеллект"
        }
    ],
    "chaos_knight": [
        {
            "name": "Рассекатель Реальности (Chaos Cleaver)",
            "icon": "⚔️",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 250,
            "base_max": 350,
            "bonus": {"crit": 45, "crit_multiplier": 80, "str": 45},
            "bonus_desc": "⚔️ +250..350 Урон | 💥 +45% Крит с множителем x3.2 | 🥩 +45 Сила"
        },
        {
            "name": "Доспех Фантомного Всадника",
            "icon": "🛡️",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 52,
            "hp_bonus": 580,
            "bonus": {"illusion_evade": 30, "str": 35},
            "bonus_desc": "🛡️ +52 Броня | ❤️ +580 HP | 🌀 30% Шанс раствориться при ударе"
        },
        {
            "name": "Око Энтропии Хаоса",
            "icon": "👁️",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"chaos_burst": 350, "all_stats": 38},
            "bonus_desc": "👑 +38 Все характеристики | 💥 Всплеск энтропии 350 ед."
        }
    ],
    "dark_tormentor": [
        {
            "name": "Тёмный Панцирь Сингулярности",
            "icon": "💎",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 56,
            "hp_bonus": 650,
            "bonus": {"reflect": 50, "magic_resist": 35},
            "bonus_desc": "🛡️ +56 Броня | ❤️ +650 HP | 🪞 Отражает 50% ЛЮБОГО входящего урона"
        },
        {
            "name": "Шипованный Кристалл Антиматерии",
            "icon": "🗡️",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 265,
            "base_max": 370,
            "bonus": {"pure_dmg": 60, "int": 45, "burst_magic": 320},
            "bonus_desc": "⚔️ +265..370 Урон | ⚡ +60 Чистый урон | 💥 Разрыв материи 320 ед."
        },
        {
            "name": "Призма Зеркального Отражения",
            "icon": "🔮",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"all_stats": 42, "reflect": 25},
            "bonus_desc": "👑 +42 Все характеристики | 🪞 +25% Дополнительное отражение"
        }
    ],
    "doom": [
        {
            "name": "Адский Палаш Рока (Doom Blade)",
            "icon": "🗡️",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 280,
            "base_max": 390,
            "bonus": {"burn": 90, "pure_dmg": 75, "str": 50},
            "bonus_desc": "⚔️ +280..390 Урон | 🔥 Горение 90/сек | 🥩 +50 Сила | ⚡ +75 Чистый урон"
        },
        {
            "name": "Нагрудник Инфернальной Ярости",
            "icon": "🦺",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 60,
            "hp_bonus": 720,
            "bonus": {"fire_aura": 80, "str": 40},
            "bonus_desc": "🛡️ +60 Броня | ❤️ +720 HP | 🔥 Адская аура выжигает 80 ед./сек"
        },
        {
            "name": "Венец Люцифера (Crown of Doom)",
            "icon": "👑",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"all_stats": 45, "silence_enemy": 20},
            "bonus_desc": "👑 +45 Все характеристики | 🤐 20% Шанс наложить безмолвие"
        }
    ],
    "primal_beast": [
        {
            "name": "Сокрушитель Материков",
            "icon": "🔨",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 300,
            "base_max": 420,
            "bonus": {"str": 65, "crit": 40, "stun_chance": 35},
            "bonus_desc": "⚔️ +300..420 Урон | 🥩 +65 Сила | 💥 35% Сокрушительный стан"
        },
        {
            "name": "Броня Доисторического Колосса",
            "icon": "🛡️",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 66,
            "hp_bonus": 850,
            "bonus": {"hp": 850, "damage_block": 75},
            "bonus_desc": "🛡️ +66 Броня | ❤️ +850 HP | 🧱 Непробиваемый блок 75 ед. урона"
        },
        {
            "name": "Сатаник Первобытной Крови (Satanic)",
            "icon": "🩸",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"lifesteal": 45, "str": 50, "unholy_rage": 1},
            "bonus_desc": "🩸 +45% Вампиризм | 🥩 +50 Сила | 😈 Нечестивая ярость"
        }
    ],
    "phantom_roshan": [
        {
            "name": "Призрачный Aegis Хаоса",
            "icon": "👻",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"hp": 400, "def": 30, "revive": 1, "all_stats": 30},
            "bonus_desc": "👑 ПРИЗРАЧНОЕ ВОСКРЕШЕНИЕ: Вторая жизнь с 100% HP! | ❤️ +400 HP | 🛡️ +30 Броня"
        },
        {
            "name": "Рапира Призрачного Владыки",
            "icon": "🗡️",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 320,
            "base_max": 450,
            "bonus": {"crit": 50, "pure_dmg": 90, "ghost_strike": 200},
            "bonus_desc": "⚔️ +320..450 Урон | 💥 +50% Крит | 👻 Призрачный удар 200 ед."
        },
        {
            "name": "Эктоплазменный Доспех Бессмертия",
            "icon": "🛡️",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 70,
            "hp_bonus": 950,
            "bonus": {"ethereal_evade": 35, "all_stats": 35},
            "bonus_desc": "🛡️ +70 Броня | ❤️ +950 HP | 👻 35% Шанс уклонения сквозь астрал"
        }
    ],
    "enigma": [
        {
            "name": "Сингулярность Энигмы (Black Hole Core)",
            "icon": "🌌",
            "type": "relic",
            "slot": "relic",
            "slot_name": "Реликвия",
            "slot_icon": "💍",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "bonus": {"all_stats": 60, "spell_amp": 60, "ult_boost": 75, "black_hole": 500},
            "bonus_desc": "🌌 СИЛА СИНГУЛЯРНОСТИ: +60 Все статы | 💥 +75% Урон Ульты | 🕳️ Черная Дыра 500"
        },
        {
            "name": "Космический Аннигилятор",
            "icon": "⚔️",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "base_min": 360,
            "base_max": 500,
            "bonus": {"pure_dmg": 120, "crit": 50, "all_stats": 40},
            "bonus_desc": "⚔️ +360..500 Урон | ⚡ +120 Чистый урон | 💥 +50% Крит | 👑 +40 Статы"
        },
        {
            "name": "Мантия Вселенской Пустоты",
            "icon": "🧥",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "immortal",
            "rarity_name": "Бессмертный",
            "rarity_color": "#eab308",
            "defense": 80,
            "hp_bonus": 1200,
            "bonus": {"void_shield": 60, "hp": 1200, "def": 80},
            "bonus_desc": "🛡️ +80 Броня | ❤️ +1200 HP | 🌌 Щит Пустоты поглощает 60% урона"
        }
    ]
}

