NATAR_HEROES_P1 = {
    "pudge": {
        "id": "pudge",
        "name": "Потрошитель (Мясник)",
        "icon": "🪝",
        "avatar": '<img src="/images/heroes/pudge.png" class="w-full h-full object-cover drop-shadow-lg">',
        "attr": "Сила",
        "desc": "Громила с гигантским тесаком и цепью. Неудержимое здоровье и регенерация плоти.",
        "base_hp": 680,
        "base_mp": 210,
        "base_speed": 190,
        "base_armor": 3.2,
        "str": 22,
        "agi": 9,
        "int": 8,
        "str_gain": 3.6,
        "agi_gain": 1.4,
        "int_gain": 1.5,
        "starter_weapon": {
            "uid": "w_starter_pudge",
            "name": "Ржавый Крюк",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🪝",
            "min_atk": 16,
            "max_atk": 24,
            "upgrade": 0,
            "bonus": {"str": 4},
            "bonus_desc": "⚔️ +16..24 Урон | 🥩 +4 Сила"
        },
        "starter_armor": {
            "uid": "a_starter_pudge",
            "name": "Фартук Мясника",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🦺",
            "defense": 8,
            "hp_bonus": 60,
            "upgrade": 0,
            "bonus": {"hp_regen": 4},
            "bonus_desc": "🛡️ +8 Броня | ❤️ +60 HP | 🩹 +4 HP/сек"
        },
        "skill": {
            "name": "Мясной Крюк & Пожирание",
            "icon": "🥩",
            "mp_cost": 25,
            "desc": "Хукает врага цепью, наносит 220% чистого урона и восстанавливает себе 50 HP!"
        },
        "skills": [
            {"key": "Q", "name": "Meat Hook", "icon": "🪝", "type": "skill", "cooldown": 10, "mp": 110, "desc": "Тяжелый крюк: стан 1.2с и чистый урон 150 + Lvl*90 + STR*1.65"},
            {"key": "E", "name": "Rot", "icon": "☣️", "type": "toggle", "cooldown": 0, "mp": 0, "desc": "Токсичное облако: замедление 25% и урон в сек 45 + Lvl*35 + MaxHP*4.5%"},
            {"key": "R", "name": "Flesh Heap", "icon": "🥩", "type": "active_passive", "cooldown": 18, "mp": 50, "desc": "Пассивно +0.5 STR за крипа (+5 за босса). Активно: щит на 150 + STR*3.2 урона"},
            {"key": "F", "name": "Dismember (ULT)", "icon": "🩸", "type": "ultimate", "cooldown": 25, "mp": 140, "desc": "Ченнелинг 3.0с: пожирает цель, 100% вампиризм, урон 350 + Lvl*200 + STR*3.8"}
        ],
        "talents": {
            10: {"left": "+25 к скорости бега", "right": "+4 к броне"},
            15: {"left": "+12% к замедлению от Rot", "right": "+2.0x урона к Meat Hook"},
            20: {"left": "+0.8 STR за заряд Flesh Heap", "right": "-4с кулдауна Meat Hook"},
            25: {"left": "Rot лечит Паджа вместо урона", "right": "1.8x длительность и вампиризм Dismember"}
        }
    },
    "juggernaut": {
        "id": "juggernaut",
        "name": "Мастер Клинка (Самурай)",
        "icon": "🗡️",
        "avatar": '<img src="/images/heroes/juggernaut.png" class="w-full h-full object-cover drop-shadow-lg">',
        "attr": "Ловкость",
        "desc": "Непревзойденный фехтовальщик бури. Шквал смертоносных ударов и ураганная скорость атаки.",
        "base_hp": 570,
        "base_mp": 230,
        "base_speed": 215,
        "base_armor": 5.0,
        "str": 13,
        "agi": 21,
        "int": 9,
        "str_gain": 2.2,
        "agi_gain": 3.0,
        "int_gain": 1.4,
        "starter_weapon": {
            "uid": "w_starter_jug",
            "name": "Катана Бури",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🗡️",
            "min_atk": 18,
            "max_atk": 26,
            "upgrade": 0,
            "bonus": {"crit": 15},
            "bonus_desc": "⚔️ +18..26 Урон | 💥 +15% Крит"
        },
        "starter_armor": {
            "uid": "a_starter_jug",
            "name": "Маска Предков",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🎭",
            "defense": 7,
            "hp_bonus": 30,
            "upgrade": 0,
            "bonus": {"dodge": 10},
            "bonus_desc": "🛡️ +7 Броня | ❤️ +30 HP | 💨 +10% Уворот"
        },
        "skill": {
            "name": "Танец Клинков (Шквал)",
            "icon": "⚡",
            "mp_cost": 25,
            "desc": "Серия из 3 молниеносных рассекающих ударов (по 130% урона с гарантированным критом)!"
        },
        "skills": [
            {"key": "Q", "name": "Blade Fury", "icon": "🌀", "type": "skill", "cooldown": 16, "mp": 100, "desc": "Вихрь клинков на 5с: 100% иммунитет к магии, +25% скорости, урон 95 + Lvl*60 + AGI*1.25/с"},
            {"key": "E", "name": "Healing Ward", "icon": "🏮", "type": "skill", "cooldown": 26, "mp": 120, "desc": "Парящий тотем на 12с: исцеляет 4% + Lvl*1.2% макс. HP в сек в радиусе 350px"},
            {"key": "R", "name": "Blade Dance", "icon": "🗡️", "type": "passive", "cooldown": 0, "mp": 0, "desc": "Пассивно: 25% + Lvl*2.5% шанс на критический удар x(2.2 + AGI*0.006)"},
            {"key": "F", "name": "Omnislash (ULT)", "icon": "⚡", "type": "ultimate", "cooldown": 42, "mp": 200, "desc": "6 + Lvl*3 молниеносных прыжков-ударов: неуязвимость, криты и +160 базового урона"}
        ],
        "talents": {
            10: {"left": "+20 к скорости бега", "right": "+5 к броне"},
            15: {"left": "+1.5с к длительности Blade Fury", "right": "+20 к скорости атаки"},
            20: {"left": "+40% к отхилу Healing Ward", "right": "+10% шанс Blade Dance"},
            25: {"left": "+1с к неуязвимости Omnislash", "right": "+1.2 к множителю крита"}
        }
    },
    "phantom_assassin": {
        "id": "phantom_assassin",
        "name": "Теневой Клинок (Убийца)",
        "icon": "🩸",
        "avatar": '<img src="/images/heroes/phantom_assassin.png" class="w-full h-full object-cover drop-shadow-lg">',
        "attr": "Ловкость",
        "desc": "Бесшумная тень ночи. Мастер уклонения от ударов и сокрушительных смертельных выпадов.",
        "base_hp": 550,
        "base_mp": 210,
        "base_speed": 220,
        "base_armor": 4.5,
        "str": 11,
        "agi": 23,
        "int": 8,
        "str_gain": 2.0,
        "agi_gain": 3.4,
        "int_gain": 1.4,
        "starter_weapon": {
            "uid": "w_starter_pa",
            "name": "Кинжал Тени",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🗡️",
            "min_atk": 17,
            "max_atk": 25,
            "upgrade": 0,
            "bonus": {"crit": 20},
            "bonus_desc": "⚔️ +17..25 Урон | 💥 +20% Крит"
        },
        "starter_armor": {
            "uid": "a_starter_pa",
            "name": "Плащ Размытия",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🥋",
            "defense": 6,
            "hp_bonus": 25,
            "upgrade": 0,
            "bonus": {"dodge": 20},
            "bonus_desc": "🛡️ +6 Броня | ❤️ +25 HP | 💨 +20% Уворот"
        },
        "skill": {
            "name": "Смертельный Выпад",
            "icon": "💥",
            "mp_cost": 20,
            "desc": "Сокрушительный выпад из тени с шансом 400% критического урона!"
        },
        "skills": [
            {"key": "Q", "name": "Stifling Dagger", "icon": "🗡️", "type": "skill", "cooldown": 4, "mp": 30, "desc": "Бросок кинжала: 80 + AGI*1.6 урона, замедление 50% на 3с, переносит крит ульты"},
            {"key": "E", "name": "Phantom Strike", "icon": "💨", "type": "skill", "cooldown": 6, "mp": 45, "desc": "Телепортация за спину врага: +160% к скорости атаки на 5 следующих ударов"},
            {"key": "R", "name": "Blur", "icon": "🌫️", "type": "active_passive", "cooldown": 25, "mp": 50, "desc": "Пассивно: 35-55% уклонения от любых ударов и пуль. Активно: невидимость на 10с"},
            {"key": "F", "name": "Coup de Grace (ULT)", "icon": "🩸", "type": "passive_ultimate", "cooldown": 0, "mp": 0, "desc": "15% шанс на чудовищный крит с множителем x3.0 / x4.5 / x6.0"}
        ],
        "talents": {
            10: {"left": "+150 к дальности кинжала", "right": "+15 урона"},
            15: {"left": "+25% вампиризма", "right": "+12% уклонения Blur"},
            20: {"left": "-2с кулдауна Phantom Strike", "right": "+3 удара с ускорением"},
            25: {"left": "+5% к шансу Coup de Grace", "right": "+2.0x к множителю крита"}
        }
    },
    "shadow_fiend": {
        "id": "shadow_fiend",
        "name": "Жнец Душ (Владыка Теней)",
        "icon": "💀",
        "avatar": '<img src="/images/heroes/shadow_fiend.png" class="w-full h-full object-cover drop-shadow-lg">',
        "attr": "Интеллект",
        "desc": "Повелевает украденными душами поверженных врагов. Испепеляющие темные взрывы и шторм душ.",
        "base_hp": 540,
        "base_mp": 270,
        "base_speed": 210,
        "base_armor": 3.5,
        "str": 10,
        "agi": 18,
        "int": 18,
        "str_gain": 1.9,
        "agi_gain": 2.8,
        "int_gain": 2.2,
        "starter_weapon": {
            "uid": "w_starter_sf",
            "name": "Осколок Тьмы",
            "type": "weapon",
            "slot": "weapon",
            "slot_name": "Оружие",
            "slot_icon": "⚔️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🔥",
            "min_atk": 18,
            "max_atk": 27,
            "upgrade": 0,
            "bonus": {"mp": 25},
            "bonus_desc": "⚔️ +18..27 Урон | 🔮 +25 Мана"
        },
        "starter_armor": {
            "uid": "a_starter_sf",
            "name": "Мантия Теней",
            "type": "armor",
            "slot": "armor",
            "slot_name": "Броня",
            "slot_icon": "🛡️",
            "rarity": "common",
            "rarity_name": "Обычный",
            "rarity_color": "#94a3b8",
            "icon": "🦹",
            "defense": 5,
            "hp_bonus": 25,
            "upgrade": 0,
            "bonus": {"mp_regen": 5},
            "bonus_desc": "🛡️ +5 Броня | ❤️ +25 HP | 🔮 +5 MP/сек"
        },
        "skill": {
            "name": "Взрыв Душ (Тройной Удар)",
            "icon": "🌑",
            "mp_cost": 25,
            "desc": "Три мощных взрыва темной энергии вокруг: суммарно 280% магического урона!"
        },
        "skills": [
            {"key": "Q", "name": "Shadowraze", "icon": "🌑", "type": "skill", "cooldown": 6, "mp": 75, "desc": "Взрывы душ: 130 + Lvl*75 + INT*1.6 урона, вешает осквернение (+90 урона следующему)"},
            {"key": "E", "name": "Necromastery", "icon": "👻", "type": "passive", "cooldown": 0, "mp": 0, "desc": "Сбор до 36 душ: каждая душа дает +3.5 урона и +1.2% к силе заклинаний"},
            {"key": "R", "name": "Presence of the Dark Lord", "icon": "👁️", "type": "passive", "cooldown": 0, "mp": 0, "desc": "Аура ужаса: снижает броню всех врагов вокруг на -5 / -9 / -13"},
            {"key": "F", "name": "Requiem of Souls (ULT)", "icon": "💥", "type": "ultimate", "cooldown": 38, "mp": 160, "desc": "Взрыв 18 волн душ: до 4500+ урона и накладывает Fear (бегство врагов) на 2.5с"}
        ],
        "talents": {
            10: {"left": "+20 к урону атак", "right": "+25 к скорости бега"},
            15: {"left": "+80 к урону от Shadowraze", "right": "+4 макс. душ"},
            20: {"left": "-3с кулдауна Shadowraze", "right": "-4 к броне ауры"},
            25: {"left": "Койлы кастуются в 2 раза быстрее", "right": "Реквием при смерти без потерь"}
        }
    }
}
