from typing import Dict, Any, List

# ==============================================================================
# RARITY MULTIPLIERS & SETTINGS
# ==============================================================================
# ==============================================================================
# MASSIVE 107-ITEM DOTA 2 & HARDCORE RPG CATALOG
# ==============================================================================

# ==============================================================================
# RARITY MULTIPLIERS & SETTINGS
# ==============================================================================

RARITY_MULTIPLIERS = {
    "common": {"name": "Обычный", "color": "#94a3b8", "mult": 1.00, "sell": 40, "affixes": 0, "weight": 50.0},
    "uncommon": {"name": "Необычный", "color": "#22c55e", "mult": 1.30, "sell": 75, "affixes": 1, "weight": 28.0},
    "rare": {"name": "Редкий", "color": "#3b82f6", "mult": 1.75, "sell": 140, "affixes": 2, "weight": 13.5},
    "epic": {"name": "Эпический", "color": "#a855f7", "mult": 2.40, "sell": 350, "affixes": 3, "weight": 6.0},
    "legendary": {"name": "Легендарный", "color": "#f59e0b", "mult": 3.40, "sell": 900, "affixes": 4, "weight": 1.9},
    "mythic": {"name": "Мифический", "color": "#ef4444", "mult": 4.80, "sell": 2500, "affixes": 5, "weight": 0.45},
    "immortal": {"name": "Бессмертный", "color": "#ec4899", "mult": 6.80, "sell": 7500, "affixes": 6, "weight": 0.15},
}

# ==============================================================================
# 28 STREAMLINED FUNCTIONAL ITEMS (natarGRP CATALOG)
# ==============================================================================

# ==============================================================================
# MASSIVE 107-ITEM DOTA 2 & HARDCORE RPG CATALOG
# ==============================================================================

NATAR_ITEMS_CATALOG = [
    # --- TIER 1: COMMON / STARTER (Levels 1 - 10) ---
    {
        "name": "Железная Ветка (Iron Branch)",
        "icon": "🌿",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "common",
        "bonus": {"str": 1, "agi": 1, "int": 1, "atk": 1},
        "bonus_desc": "🌿 +1 ко всем характеристикам | ⚔️ +1 Урон"
    },
    {
        "name": "Перчатки Силы (Gauntlets of Strength)",
        "icon": "🥊",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "common",
        "bonus": {"str": 3, "hp": 35},
        "bonus_desc": "💪 +3 Сила | ❤️ +35 HP"
    },
    {
        "name": "Тапочки Ловкости (Slippers of Agility)",
        "icon": "🥿",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "common",
        "bonus": {"agi": 3, "dodge": 1},
        "bonus_desc": "🏃 +3 Ловкость | 💨 +1% Уворот"
    },
    {
        "name": "Мантия Интеллекта (Mantle of Intelligence)",
        "icon": "📜",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "common",
        "bonus": {"int": 3, "mp": 30},
        "bonus_desc": "🔮 +3 Интеллект | 💧 +30 MP"
    },
    {
        "name": "Венец Благородства (Circlet)",
        "icon": "👑",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "common",
        "bonus": {"str": 2, "agi": 2, "int": 2},
        "bonus_desc": "✨ +2 ко всем характеристикам"
    },
    {
        "name": "Топорик Лесоруба (Quelling Blade)",
        "icon": "🪓",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "common",
        "base_min": 4,
        "base_max": 7,
        "bonus": {"creep_dmg": 4},
        "bonus_desc": "⚔️ +4..7 Урон | 🌲 +4 доп. урона по крипам"
    },
    {
        "name": "Прочный Щиток (Stout Shield)",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "common",
        "base_def": 3,
        "base_hp": 25,
        "bonus": {"block": 6},
        "bonus_desc": "🛡️ +3 Броня | 🛡️ Блокирует 6 урона"
    },
    {
        "name": "Кольцо Защиты (Ring of Protection)",
        "icon": "💍",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "common",
        "base_def": 2,
        "base_hp": 15,
        "bonus": {"def": 2},
        "bonus_desc": "🛡️ +2 Броня | ❤️ +15 HP"
    },
    {
        "name": "Волшебная Палочка (Magic Stick)",
        "icon": "🪄",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "common",
        "bonus": {"hp": 15, "mp": 20},
        "bonus_desc": "❤️ +15 HP | 💧 +20 MP"
    },
    {
        "name": "Камень Порчи (Blight Stone)",
        "icon": "🪨",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "common",
        "base_min": 3,
        "base_max": 5,
        "bonus": {"armor_pierce": 1},
        "bonus_desc": "⚔️ +3..5 Урон | 🩸 -1 Брони врага"
    },
    {
        "name": "Шнурок Ветра (Wind Lace)",
        "icon": "👟",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "common",
        "base_def": 1,
        "base_hp": 10,
        "bonus": {"dodge": 2},
        "bonus_desc": "💨 +2% Уворот | 🛡️ +1 Броня"
    },
    {
        "name": "Капли Дождя (Infused Raindrops)",
        "icon": "💧",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "common",
        "bonus": {"hp": 30, "mp_regen": 1},
        "bonus_desc": "❤️ +30 HP | 💧 +1 MP/сек"
    },
    {
        "name": "Ржавый Кинжал Новичка",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "common",
        "base_min": 5,
        "base_max": 8,
        "bonus": {"crit": 2},
        "bonus_desc": "⚔️ +5..8 Урон | 💥 +2% Крит"
    },
    {
        "name": "Тканевая Куртка Ополченца",
        "icon": "🥋",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "common",
        "base_def": 2,
        "base_hp": 25,
        "bonus": {},
        "bonus_desc": "🛡️ +2 Броня | ❤️ +25 HP"
    },
    {
        "name": "Кольцо Регенерации (Ring of Regen)",
        "icon": "💚",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "common",
        "bonus": {"hp_regen": 2},
        "bonus_desc": "💚 +2 HP в секунду"
    },
    {
        "name": "Дубовый Боевой Посох",
        "icon": "🪵",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "common",
        "base_min": 4,
        "base_max": 7,
        "bonus": {"int": 2},
        "bonus_desc": "⚔️ +4..7 Урон | 🔮 +2 Интеллект"
    },

    # --- TIER 2: UNCOMMON / EARLY GAME (Levels 10 - 30) ---
    {
        "name": "Клинки Атаки (Blades of Attack)",
        "icon": "⚔️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "uncommon",
        "base_min": 9,
        "base_max": 14,
        "bonus": {"atk": 4},
        "bonus_desc": "⚔️ +9..14 Урон | 💥 +4 Базовый урон"
    },
    {
        "name": "Кольчуга (Chainmail)",
        "icon": "🦺",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 5,
        "base_hp": 60,
        "bonus": {"def": 2},
        "bonus_desc": "🛡️ +5 Броня | ❤️ +60 HP"
    },
    {
        "name": "Шлем Железной Воли (Helm of Iron Will)",
        "icon": "🪖",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 6,
        "base_hp": 90,
        "bonus": {"hp_regen": 4},
        "bonus_desc": "🛡️ +6 Броня | 💚 +4 HP/сек | ❤️ +90 HP"
    },
    {
        "name": "Маска Смерти (Morbid Mask)",
        "icon": "🎭",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "uncommon",
        "bonus": {"lifesteal": 7},
        "bonus_desc": "🧛 +7% Вампиризм от атак"
    },
    {
        "name": "Сапоги Скорости (Boots of Speed)",
        "icon": "👢",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 3,
        "base_hp": 40,
        "bonus": {"dodge": 5},
        "bonus_desc": "💨 +5% Уворот | 🛡️ +3 Броня"
    },
    {
        "name": "Фазовые Сапоги (Phase Boots)",
        "icon": "👢",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 4,
        "base_hp": 70,
        "bonus": {"atk": 12, "dodge": 4},
        "bonus_desc": "⚔️ +12 Урон | 🛡️ +4 Броня | 💨 +4% Уворот"
    },
    {
        "name": "Сапоги Мощи (Power Treads)",
        "icon": "🥾",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 4,
        "base_hp": 95,
        "bonus": {"all_stats": 5, "atk": 8},
        "bonus_desc": "✨ +5 ко всем характеристикам | ⚔️ +8 Урон"
    },
    {
        "name": "Сфера Коррозии (Orb of Corrosion)",
        "icon": "🧪",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "uncommon",
        "base_min": 10,
        "base_max": 16,
        "bonus": {"armor_pierce": 3, "hp": 50},
        "bonus_desc": "⚔️ +10..16 Урон | 🩸 -3 Брони врага | ❤️ +50 HP"
    },
    {
        "name": "Клинок Сокола (Falcon Blade)",
        "icon": "🪶",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "uncommon",
        "base_min": 12,
        "base_max": 18,
        "bonus": {"hp": 120, "mp": 50},
        "bonus_desc": "⚔️ +12..18 Урон | ❤️ +120 HP | 💧 +50 MP"
    },
    {
        "name": "Авангард (Vanguard)",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 7,
        "base_hp": 180,
        "bonus": {"block": 18, "hp_regen": 5},
        "bonus_desc": "🛡️ +7 Броня | ❤️ +180 HP | 🛡️ Блок 18 урона | 💚 +5 HP/сек"
    },
    {
        "name": "Урна Теней (Urn of Shadows)",
        "icon": "🏺",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "uncommon",
        "bonus": {"all_stats": 2, "armor": 2, "hp_regen": 2},
        "bonus_desc": "✨ +2 Статы | 🛡️ +2 Броня | 💚 +2 HP/сек"
    },
    {
        "name": "Медальон Мужества (Medallion of Courage)",
        "icon": "🏅",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 5,
        "base_hp": 75,
        "bonus": {"armor_pierce": 3},
        "bonus_desc": "🛡️ +5 Броня | 🩸 -3 Брони врага при ударе"
    },
    {
        "name": "Корона Императора (Crown)",
        "icon": "👑",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "uncommon",
        "bonus": {"str": 4, "agi": 4, "int": 4},
        "bonus_desc": "👑 +4 ко всем характеристикам"
    },
    {
        "name": "Пояс Великана (Belt of Strength)",
        "icon": "🥋",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 3,
        "base_hp": 110,
        "bonus": {"str": 6},
        "bonus_desc": "💪 +6 Сила | ❤️ +110 HP"
    },
    {
        "name": "Сапоги Эльфийской Ловкости (Boots of Elvenskin)",
        "icon": "🥿",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 3,
        "base_hp": 40,
        "bonus": {"agi": 6, "dodge": 3},
        "bonus_desc": "🏃 +6 Ловкость | 💨 +3% Уворот"
    },
    {
        "name": "Мантия Мага (Robe of the Magi)",
        "icon": "👘",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "uncommon",
        "base_def": 3,
        "base_hp": 30,
        "bonus": {"int": 6, "mp": 60},
        "bonus_desc": "🔮 +6 Интеллект | 💧 +60 MP"
    },

    # --- TIER 3: RARE / MID GAME (Levels 30 - 60) ---
    {
        "name": "Палаш (Broadsword)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 18,
        "base_max": 28,
        "bonus": {"atk": 6},
        "bonus_desc": "⚔️ +18..28 Урон | 💥 +6 Урон"
    },
    {
        "name": "Клеймор (Claymore)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 24,
        "base_max": 36,
        "bonus": {"atk": 8},
        "bonus_desc": "⚔️ +24..36 Урон | 💥 +8 Урон"
    },
    {
        "name": "Мифриловый Молот (Mithril Hammer)",
        "icon": "🔨",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 30,
        "base_max": 44,
        "bonus": {"crit": 4},
        "bonus_desc": "⚔️ +30..44 Урон | 💥 +4% Крит"
    },
    {
        "name": "Латный Доспех (Platemail)",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "rare",
        "base_def": 11,
        "base_hp": 160,
        "bonus": {"def": 4},
        "bonus_desc": "🛡️ +11 Броня | ❤️ +160 HP"
    },
    {
        "name": "Кристалис (Crystalys)",
        "icon": "💎",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 34,
        "base_max": 48,
        "bonus": {"crit": 15},
        "bonus_desc": "⚔️ +34..48 Урон | 💥 +15% шанс Крита (x1.75)"
    },
    {
        "name": "Крушитель Черепов (Skull Basher)",
        "icon": "🔨",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 28,
        "base_max": 42,
        "bonus": {"str": 10, "stun_chance": 12},
        "bonus_desc": "⚔️ +28..42 Урон | 💪 +10 Сила | 💫 12% Шанс Оглушения"
    },
    {
        "name": "Теневой Клинок (Shadow Blade)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 32,
        "base_max": 46,
        "bonus": {"dodge": 12, "atk": 10},
        "bonus_desc": "⚔️ +32..46 Урон | 💨 +12% Уворот | 💥 +10 Урон"
    },
    {
        "name": "Яша (Yasha)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 22,
        "base_max": 34,
        "bonus": {"agi": 16, "speed": 10, "dodge": 6},
        "bonus_desc": "🏃 +16 Ловкость | ⚡ +10% Скорость атаки | 💨 +6% Уворот"
    },
    {
        "name": "Саша (Sange)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 22,
        "base_max": 34,
        "bonus": {"str": 16, "hp": 180, "lifesteal": 6},
        "bonus_desc": "💪 +16 Сила | ❤️ +180 HP | 🧛 +6% Вампиризм"
    },
    {
        "name": "Кайя (Kaya)",
        "icon": "🪄",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 20,
        "base_max": 32,
        "bonus": {"int": 16, "mp": 150, "spell_amp": 10},
        "bonus_desc": "🔮 +16 Интеллект | 💧 +150 MP | ✨ +10% Сила заклинаний"
    },
    {
        "name": "Молния (Maelstrom)",
        "icon": "⚡",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 26,
        "base_max": 40,
        "bonus": {"chain_lightning": 25},
        "bonus_desc": "⚔️ +26..40 Урон | ⚡ 25% Шанс выпустить Цепную Молнию"
    },
    {
        "name": "Клинок Очищения (Diffusal Blade)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 25,
        "base_max": 38,
        "bonus": {"agi": 15, "mana_burn": 30},
        "bonus_desc": "🏃 +15 Ловкость | 💧 Сожжение 30 маны за удар"
    },
    {
        "name": "Пика Дракона (Dragon Lance)",
        "icon": "🔱",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 24,
        "base_max": 36,
        "bonus": {"str": 12, "agi": 12, "hp": 140},
        "bonus_desc": "💪 +12 Сила | 🏃 +12 Ловкость | ❤️ +140 HP"
    },
    {
        "name": "Возвратный Доспех (Blade Mail)",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "rare",
        "base_def": 8,
        "base_hp": 130,
        "bonus": {"atk": 16, "reflect": 25},
        "bonus_desc": "🛡️ +8 Броня | ⚔️ +16 Урон | 🔄 Отражает 25% урона"
    },
    {
        "name": "Аганимный Осколок (Aghanim Shard)",
        "icon": "🔷",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "rare",
        "bonus": {"all_stats": 8, "ult_cd": 15},
        "bonus_desc": "👑 +8 ко всем характеристикам | ⏱️ -15% КД Ульты"
    },
    {
        "name": "Саша и Яша (Sange and Yasha)",
        "icon": "⚔️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 36,
        "base_max": 52,
        "bonus": {"str": 16, "agi": 16, "dodge": 8, "lifesteal": 6},
        "bonus_desc": "💪 +16 Сила | 🏃 +16 Ловкость | 💨 +8% Уворот | 🧛 +6% Вампиризм"
    },

    # --- TIER 4: EPIC / LATE GAME (Levels 60 - 90) ---
    {
        "name": "Боевой Топор (Battle Fury)",
        "icon": "🪓",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 60,
        "base_max": 88,
        "bonus": {"cleave": 45, "hp_regen": 8},
        "bonus_desc": "⚔️ +60..88 Урон | 💥 45% Сплэш урон вокруг | 💚 +8 HP/сек"
    },
    {
        "name": "Дедал (Daedalus)",
        "icon": "🏹",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 85,
        "base_max": 125,
        "bonus": {"crit": 30},
        "bonus_desc": "⚔️ +85..125 Урон | 💥 +30% Шанс Крита (x2.25)"
    },
    {
        "name": "Бабочка (Butterfly)",
        "icon": "🦋",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 45,
        "base_max": 68,
        "bonus": {"agi": 35, "dodge": 32, "atk": 25},
        "bonus_desc": "🏃 +35 Ловкость | 💨 +32% Уворот | ⚔️ +25 Базовый урон"
    },
    {
        "name": "Обезьяний Посох (Monkey King Bar)",
        "icon": "🐒",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 52,
        "base_max": 78,
        "bonus": {"true_strike": 80, "atk": 30},
        "bonus_desc": "⚔️ +52..78 Урон | 🎯 80% Истинный удар сквозь увороты"
    },
    {
        "name": "Сияние (Radiance)",
        "icon": "☀️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 60,
        "base_max": 85,
        "bonus": {"burn_aura": 65, "dodge": 15},
        "bonus_desc": "⚔️ +60..85 Урон | 🔥 Аура Ожога 65 урона/сек | 💨 +15% Уворот"
    },
    {
        "name": "Опустошитель (Desolator)",
        "icon": "🔴",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 58,
        "base_max": 82,
        "bonus": {"armor_pierce": 6},
        "bonus_desc": "⚔️ +58..82 Урон | 🩸 Снижает броню врага на 6"
    },
    {
        "name": "Сатаник (Satanic)",
        "icon": "🩸",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "epic",
        "bonus": {"str": 25, "atk": 35, "lifesteal": 28},
        "bonus_desc": "💪 +25 Сила | ⚔️ +35 Урон | 🧛 +28% Вампиризм"
    },
    {
        "name": "Сердце Тарраска (Heart of Tarrasque)",
        "icon": "❤️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "epic",
        "base_def": 8,
        "base_hp": 650,
        "bonus": {"str": 45, "hp_regen_pct": 2},
        "bonus_desc": "💪 +45 Сила | ❤️ +650 HP | 💚 Регенерация +2% Макс. HP/сек"
    },
    {
        "name": "Кираса Штурма (Assault Cuirass)",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "epic",
        "base_def": 18,
        "base_hp": 300,
        "bonus": {"armor_aura": 5, "atk_speed": 35},
        "bonus_desc": "🛡️ +18 Броня | 🛡️ +5 Броня Аура | ⚡ +35% Скорость атаки"
    },
    {
        "name": "Черный Королевский Бар (Black King Bar)",
        "icon": "🟡",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "epic",
        "bonus": {"str": 12, "atk": 25, "magic_immune": 1},
        "bonus_desc": "💪 +12 Сила | ⚔️ +25 Урон | 🛡️ Иммунитет к оглушениям"
    },
    {
        "name": "Страж Шивы (Shiva Guard)",
        "icon": "❄️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "epic",
        "base_def": 16,
        "base_hp": 280,
        "bonus": {"int": 30, "slow_aura": 25},
        "bonus_desc": "🛡️ +16 Броня | 🔮 +30 Интеллект | ❄️ Ледяная Аура замедления"
    },
    {
        "name": "Око Скади (Eye of Skadi)",
        "icon": "👁️",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "epic",
        "bonus": {"all_stats": 25, "hp": 300, "mp": 300, "slow": 30},
        "bonus_desc": "✨ +25 ко всем статам | ❤️ +300 HP | ❄️ Атаки замедляют на 30%"
    },
    {
        "name": "Кровавый Шип (Bloodthorn)",
        "icon": "🌹",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 56,
        "base_max": 84,
        "bonus": {"int": 25, "crit": 25, "silence": 1},
        "bonus_desc": "⚔️ +56..84 Урон | 🔮 +25 Интеллект | 💥 +25% Крит"
    },
    {
        "name": "Мьёльнир (Mjollnir)",
        "icon": "⚡",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 35,
        "base_max": 55,
        "bonus": {"atk_speed": 65, "static_shield": 1},
        "bonus_desc": "⚔️ +35..55 Урон | ⚡ +65% Скорость атаки | ⚡ Статический Щит"
    },
    {
        "name": "Коса Вайса (Scythe of Vyse)",
        "icon": "🐏",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "epic",
        "bonus": {"int": 35, "str": 10, "agi": 10, "hex": 1},
        "bonus_desc": "🔮 +35 Интеллект | ✨ Хекс (превращение врага в овечку)"
    },
    {
        "name": "Абиссальный Клинок (Abyssal Blade)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 45,
        "base_max": 70,
        "bonus": {"str": 10, "hp": 250, "stun_active": 1},
        "bonus_desc": "⚔️ +45..70 Урон | 💪 +10 Сила | 💫 Оглушающий Удар"
    },

    # --- TIER 5: IMMORTAL / ANCIENT ARTIFACTS (Levels 90 - 150+) ---
    {
        "name": "Божественная Рапира (Divine Rapier)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "base_min": 250,
        "base_max": 380,
        "bonus": {"crit": 20},
        "bonus_desc": "👑 ВЫСШИЙ КЛИНОК: ⚔️ +250..380 Урон | 💥 +20% Крит (x2.5)"
    },
    {
        "name": "Эгида Бессмертия (Aegis of the Immortal)",
        "icon": "🛡️",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "bonus": {"hp": 500, "def": 15, "revive": 1},
        "bonus_desc": "👑 ВТОРАЯ ЖИЗНЬ: Воскрешение при гибели с 100% HP! | ❤️ +500 HP | 🛡️ +15 Броня"
    },
    {
        "name": "Сыр Рошана (Cheese)",
        "icon": "🧀",
        "type": "potion",
        "slot": "consumable",
        "slot_name": "Зелье",
        "slot_icon": "🧪",
        "rarity": "immortal",
        "count": 3,
        "heal_hp": 9999,
        "heal_mp": 9999,
        "bonus": {"full_heal": 1},
        "bonus_desc": "🧀 Мгновенно восстанавливает 100% HP и 100% MP (3 порции)!"
    },
    {
        "name": "Благословение Аганима (Aghanim Blessing)",
        "icon": "🔮",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "bonus": {"all_stats": 25, "hp": 350, "mp": 350, "ult_boost": 40},
        "bonus_desc": "👑 +25 Статы | ❤️ +350 HP | 💧 +350 MP | 💥 +40% Урон Ульты"
    },
    {
        "name": "Сфера Обновления (Refresher Orb)",
        "icon": "🟢",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "bonus": {"hp_regen": 15, "mp_regen": 12, "refresh": 1},
        "bonus_desc": "🔄 Мгновенно сбрасывает время перезарядки всех скиллов"
    },
    {
        "name": "Апекс (Apex)",
        "icon": "🔺",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "bonus": {"primary_attr": 75, "hp": 400},
        "bonus_desc": "👑 +75 к Основному Атрибуту (+75 Урон) | ❤️ +400 HP"
    },
    {
        "name": "Падшие Небеса (Fallen Sky)",
        "icon": "☄️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "base_min": 120,
        "base_max": 190,
        "bonus": {"str": 25, "meteor": 250},
        "bonus_desc": "⚔️ +120..190 Урон | ☄️ Падение Метеора оглушает на 3 сек"
    },
    {
        "name": "Зеркальный Щит (Mirror Shield)",
        "icon": "🪞",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "immortal",
        "base_def": 25,
        "base_hp": 600,
        "bonus": {"all_stats": 18, "reflect": 50},
        "bonus_desc": "🛡️ +25 Броня | ❤️ +600 HP | 🪞 50% Шанс Отразить любое заклинание"
    },
    {
        "name": "Гигантское Кольцо (Giant Ring)",
        "icon": "💍",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "immortal",
        "base_def": 20,
        "base_hp": 1200,
        "bonus": {"str": 50, "giant_stomp": 100},
        "bonus_desc": "💪 +50 Сила | ❤️ +1200 HP | 🦶 Топот растаптывает врагов"
    },
    {
        "name": "Стигийский Дезолятор (Stygian Desolator)",
        "icon": "🩸",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "base_min": 140,
        "base_max": 220,
        "bonus": {"armor_pierce": 12},
        "bonus_desc": "⚔️ +140..220 Урон | 🩸 РАССЕКАЕТ БРОНЮ ВРАГА НА -12"
    },
    {
        "name": "Око Вечности (Eye of Eternity)",
        "icon": "👁️",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "bonus": {"all_stats": 35, "hp": 800, "mp": 800, "atk": 80},
        "bonus_desc": "👑 ВЕЛИКИЙ АРТЕФАКТ: +35 Все статы | ❤️ +800 HP | 💧 +800 MP | ⚔️ +80 Урон"
    }
,
{   'base_max': 7,
    'base_min': 4,
    'bonus': {'int': 2, 'magic_dmg': 3},
    'bonus_desc': '⚔️ +4..7 Урон | 🔮 +2 Интеллект | ⚡ +3 Магич. урон',
    'icon': '🦯',
    'name': 'Дубовый Посох (Oak Staff)',
    'rarity': 'common',
    'slot': 'weapon',
    'slot_icon': '⚔️',
    'slot_name': 'Оружие',
    'type': 'weapon'},
{   'base_max': 6,
    'base_min': 3,
    'bonus': {'agi': 1, 'atk_speed': 4},
    'bonus_desc': '⚔️ +3..6 Урон | 🏃 +1 Ловкость | ⚡ +4% Скор. атаки',
    'icon': '🗡️',
    'name': 'Ржавый Кинжал (Rusty Dagger)',
    'rarity': 'common',
    'slot': 'weapon',
    'slot_icon': '⚔️',
    'slot_name': 'Оружие',
    'type': 'weapon'},
{   'base_def': 2,
    'base_hp': 25,
    'bonus': {'block': 5},
    'bonus_desc': '🛡️ +2 Броня | ❤️ +25 HP | 🛡️ Блок 5 урона',
    'icon': '🛡️',
    'name': 'Деревянный Баклер (Wooden Buckler)',
    'rarity': 'common',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'bonus': {'hp': 25, 'mp': 15},
    'bonus_desc': '❤️ +25 HP | 💧 +15 MP',
    'icon': '💎',
    'name': 'Треснувший Опал (Cracked Opal)',
    'rarity': 'common',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'atk': 2, 'mp_regen': 1.2},
    'bonus_desc': '⚔️ +2 Урон | 💧 +1.2 Реген MP/сек',
    'icon': '💍',
    'name': 'Кольцо Базилиуса (Ring of Basilius)',
    'rarity': 'common',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'base_max': 8,
    'base_min': 5,
    'bonus': {'creep_dmg': 6, 'str': 2},
    'bonus_desc': '⚔️ +5..8 Урон | 💪 +2 Сила | 🌲 +6 Урон по крипам',
    'icon': '🪓',
    'name': 'Топорик Лесоруба (Woodcutter Hatchet)',
    'rarity': 'common',
    'slot': 'weapon',
    'slot_icon': '⚔️',
    'slot_name': 'Оружие',
    'type': 'weapon'},
{   'base_def': 1,
    'base_hp': 20,
    'bonus': {'int': 2, 'mp': 20},
    'bonus_desc': '🛡️ +1 Броня | ❤️ +20 HP | 🔮 +2 Интеллект',
    'icon': '🎗️',
    'name': 'Повязка Ученика (Apprentice Band)',
    'rarity': 'common',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'bonus': {'agi': 2, 'dodge': 2},
    'bonus_desc': '🏃 +2 Ловкость | 💨 +2% Шанс Уворота',
    'icon': '🎗️',
    'name': 'Шнурок Проворства (Lace of Haste)',
    'rarity': 'common',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'atk': 3, 'hp': 60, 'hp_regen': 1.0, 'str': 5},
    'bonus_desc': '💪 +5 Сила | ⚔️ +3 Урон | ❤️ +60 HP | 🩸 +1.0 HP/сек',
    'icon': '🥊',
    'name': 'Брейсер Защитника (Bracer)',
    'rarity': 'uncommon',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'agi': 5, 'atk_speed': 6, 'def': 2},
    'bonus_desc': '🏃 +5 Ловкость | 🛡️ +2 Броня | ⚡ +6% Скор. атаки',
    'icon': '💍',
    'name': 'Врейс Бенд (Wraith Band)',
    'rarity': 'uncommon',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'int': 5, 'mp': 60, 'spell_amp': 3},
    'bonus_desc': '🔮 +5 Интеллект | 💧 +60 MP | ✨ +3% Сила магии',
    'icon': '📿',
    'name': 'Нулл Талисман (Null Talisman)',
    'rarity': 'uncommon',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'def': 2, 'hp_regen': 1.5, 'str': 6},
    'bonus_desc': '💪 +6 Сила | 🛡️ +2 Броня | 🩸 +1.5 HP/сек',
    'icon': '💍',
    'name': 'Кольцо Души (Soul Ring)',
    'rarity': 'uncommon',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'hp': 100, 'hp_regen': 2.0},
    'bonus_desc': '❤️ +100 HP | 🩸 +2.0 Реген HP/сек',
    'icon': '💧',
    'name': 'Капля Жизни (Tear of Life)',
    'rarity': 'uncommon',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'base_def': 3,
    'base_hp': 75,
    'bonus': {'magic_resist': 12},
    'bonus_desc': '🛡️ +3 Броня | ❤️ +75 HP | 🔮 +12% Магич. сопротивление',
    'icon': '🧥',
    'name': 'Плащ Мудрости (Cloak of Wisdom)',
    'rarity': 'uncommon',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'base_max': 20,
    'base_min': 14,
    'bonus': {'agi': 4, 'crit_chance': 4},
    'bonus_desc': '⚔️ +14..20 Урон | 🏃 +4 Ловкость | 🎯 +4% Шанс Крита',
    'icon': '🗡️',
    'name': 'Кинжал Тени (Shadow Dagger)',
    'rarity': 'uncommon',
    'slot': 'weapon',
    'slot_icon': '⚔️',
    'slot_name': 'Оружие',
    'type': 'weapon'},
{   'bonus': {'agi': 7, 'atk': 7, 'def': 2, 'int': 3, 'str': 3},
    'bonus_desc': '🏃 +7 Ловк | 💪 +3 Сила | 🔮 +3 Инт | ⚔️ +7 Урон | 🛡️ +2 Броня',
    'icon': '💍',
    'name': 'Кольцо Аквилы (Ring of Aquila)',
    'rarity': 'uncommon',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'atk_speed': 14, 'int': 7, 'str': 7},
    'bonus_desc': '💪 +7 Сила | 🔮 +7 Инт | ⚡ +14% Скор. Атаки аура',
    'icon': '🥁',
    'name': 'Барабаны Войны (Drum of Endurance)',
    'rarity': 'rare',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'atk_percent': 12, 'def': 4, 'lifesteal': 15},
    'bonus_desc': '🛡️ +4 Броня | 🩸 +15% Вампиризм | ⚔️ +12% Бонус урона',
    'icon': '🦇',
    'name': 'Владимир (Vladmir Offering)',
    'rarity': 'rare',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'base_def': 8,
    'base_hp': 200,
    'bonus': {'all_stats': 6, 'dodge': 6},
    'bonus_desc': '🛡️ +8 Броня | ❤️ +200 HP | 🌟 +6 Все статы | 💨 +6% Уворот',
    'icon': '☀️',
    'name': 'Солар Крест (Solar Crest)',
    'rarity': 'rare',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'bonus': {'int': 12, 'mp': 300, 'mp_regen': 2.5, 'spell_amp': 8},
    'bonus_desc': '🔮 +12 Инт | 💧 +300 MP | 💧 +2.5 MP/сек | ✨ +8% Сила магии',
    'icon': '🔍',
    'name': 'Линза Эфира (Aether Lens)',
    'rarity': 'rare',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'base_def': 5,
    'base_hp': 180,
    'bonus': {'dodge': 8, 'magic_resist': 20},
    'bonus_desc': '🛡️ +5 Броня | ❤️ +180 HP | 🔮 +20% Маг. Резист | 💨 +8% Уворот',
    'icon': '🧥',
    'name': 'Плащ Мерцания (Glimmer Cape)',
    'rarity': 'rare',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'base_max': 42,
    'base_min': 28,
    'bonus': {'atk_speed': 10, 'double_strike': 15, 'str': 12},
    'bonus_desc': '⚔️ +28..42 Урон | 💪 +12 Сила | ⚡ 15% Шанс Двойного Удара',
    'icon': '⚔️',
    'name': 'Эхо Сабля (Echo Sabre)',
    'rarity': 'rare',
    'slot': 'weapon',
    'slot_icon': '⚔️',
    'slot_name': 'Оружие',
    'type': 'weapon'},
{   'base_max': 48,
    'base_min': 32,
    'bonus': {'hp_regen': 3.0, 'int': 12, 'str': 12},
    'bonus_desc': '⚔️ +32..48 Урон | 💪 +12 Сила | 🔮 +12 Инт | ☄️ Огненный удар',
    'icon': '☄️',
    'name': 'Метеор Хаммер (Meteor Hammer)',
    'rarity': 'rare',
    'slot': 'weapon',
    'slot_icon': '⚔️',
    'slot_name': 'Оружие',
    'type': 'weapon'},
{   'base_max': 50,
    'base_min': 35,
    'bonus': {'agi': 10, 'int': 8, 'str': 10},
    'bonus_desc': '⚔️ +35..50 Урон | 🌟 +10 Сила/Ловкость | 🔱 Притягивает крипов',
    'icon': '🔱',
    'name': 'Меч Гарпуна (Harpoon Blade)',
    'rarity': 'rare',
    'slot': 'weapon',
    'slot_icon': '⚔️',
    'slot_name': 'Оружие',
    'type': 'weapon'},
{   'base_max': 95,
    'base_min': 65,
    'bonus': {'agi': 12, 'chain_lightning': 25, 'int': 24},
    'bonus_desc': '⚔️ +65..95 Урон | 🔮 +24 Инт | ⚡ 25% Цепная Молния 180 урона',
    'icon': '⚡',
    'name': 'Крикун Глейпнир (Gleipnir)',
    'rarity': 'epic',
    'slot': 'weapon',
    'slot_icon': '⚔️',
    'slot_name': 'Оружие',
    'type': 'weapon'},
{   'base_def': 16,
    'base_hp': 450,
    'bonus': {'damage_block': 40, 'str': 15},
    'bonus_desc': '🛡️ +16 Броня | ❤️ +450 HP | 💪 +15 Сила | 🛡️ Блок 40 урона',
    'icon': '🛡️',
    'name': 'Кримсон Гард (Crimson Guard)',
    'rarity': 'epic',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'base_def': 10,
    'base_hp': 400,
    'bonus': {'hp_regen': 6.0, 'magic_resist': 30},
    'bonus_desc': '🛡️ +10 Броня | ❤️ +400 HP | 🔮 +30% Маг. Резист | 🩸 +6 HP/сек',
    'icon': '🪈',
    'name': 'Трубка Прозрения (Pipe of Insight)',
    'rarity': 'epic',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'base_def': 12,
    'base_hp': 350,
    'bonus': {'combo_shield': 1, 'mp': 350},
    'bonus_desc': '🛡️ +12 Броня | ❤️ +350 HP | 💧 +350 MP | 🛡️ Неуязвимость при низком HP',
    'icon': '📀',
    'name': 'Эон Диск (Aeon Disk)',
    'rarity': 'epic',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'bonus': {'int': 35, 'move_speed': 15, 'mp_regen': 4.0},
    'bonus_desc': '🔮 +35 Инт | 💧 +4.0 MP/сек | 🌪️ Циклон неуязвимости',
    'icon': '🌪️',
    'name': 'Винд Вейкер (Wind Waker)',
    'rarity': 'epic',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'atk': 45, 'int': 25, 'magic_pierce': 20},
    'bonus_desc': '🔮 +25 Инт | ⚔️ +45 Урон | 👻 Атаки пробивают сопротивление магии',
    'icon': '👻',
    'name': 'Брошь Призрака (Revenant Brooch)',
    'rarity': 'epic',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'cooldown_reduct': 25, 'hp': 425, 'mp': 725},
    'bonus_desc': '❤️ +425 HP | 💧 +725 MP | ⏱️ -25% Время перезарядки способностей',
    'icon': '🔮',
    'name': 'Октарин Ядро (Octarine Core)',
    'rarity': 'epic',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'all_stats': 16, 'hp_regen': 4.0, 'mp_regen': 3.0},
    'bonus_desc': '🌟 +16 Все атрибуты | 🩸 +4 HP/сек | 🛡️ Блокирует опасные заклинания',
    'icon': '🌐',
    'name': 'Сфера Линкена (Linken Sphere)',
    'rarity': 'epic',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'bonus': {'hp': 750, 'int': 30, 'str': 30, 'summon_demons': 4},
    'bonus_desc': '👑 ВЕЛИКИЙ АРТЕФАКТ: 💪 +30 Сила | 🔮 +30 Инт | 💀 Призыв 4 демонов',
    'icon': '📖',
    'name': 'Книга Мертвых (Book of the Dead)',
    'rarity': 'immortal',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'base_def': 20,
    'base_hp': 900,
    'bonus': {'atk_speed': 40, 'gold_boost': 25},
    'bonus_desc': '🛡️ +20 Броня | ❤️ +900 HP | ⚡ +40% Скор. Атаки | 🪙 +25% Больше золота',
    'icon': '🏴\u200d☠️',
    'name': 'Пиратская Шляпа (Pirate Hat)',
    'rarity': 'immortal',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'base_def': 18,
    'base_hp': 850,
    'bonus': {'dispel': 1, 'hp_regen': 10.0, 'move_speed': 30},
    'bonus_desc': '🛡️ +18 Броня | ❤️ +850 HP | 🩸 +10 HP/сек | 💨 Сверхбыстрый рывок и сброс станов',
    'icon': '👢',
    'name': 'Сапоги Силы (Force Boots)',
    'rarity': 'immortal',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'},
{   'bonus': {'mp': 800, 'mp_regen': 10.0, 'spell_amp': 25, 'truesight': 1},
    'bonus_desc': '💧 +800 MP | 💧 +10 MP/сек | ✨ +25% Сила Заклинаний | 👁️ Истинное Зрение',
    'icon': '🔮',
    'name': 'Камень Провидца (Seer Stone)',
    'rarity': 'immortal',
    'slot': 'relic',
    'slot_icon': '💍',
    'slot_name': 'Реликвия',
    'type': 'relic'},
{   'base_def': 28,
    'base_hp': 1100,
    'bonus': {'all_stats': 25, 'instant_refresh': 1},
    'bonus_desc': '🛡️ +28 Броня | ❤️ +1100 HP | 🌟 +25 Все характеристики | ⚙️ Сброс всех кулдаунов',
    'icon': '⚙️',
    'name': 'Экс Махина (Ex Machina)',
    'rarity': 'immortal',
    'slot': 'armor',
    'slot_icon': '🛡️',
    'slot_name': 'Броня',
    'type': 'armor'}
,
    # --- EXPANDED DOTA 2 MAGE & AGILITY ARTIFACTS ---
    {
        "name": "Посох Чародея (Staff of Wizardry)",
        "icon": "🪄",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "uncommon",
        "base_min": 15,
        "base_max": 24,
        "bonus": {"int": 10, "mp": 80, "spell_amp": 5},
        "bonus_desc": "🔮 +10 Интеллект | 💧 +80 MP | ✨ +5% Сила заклинаний"
    },
    {
        "name": "Клинок Ловкости (Blade of Alacrity)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "uncommon",
        "base_min": 16,
        "base_max": 25,
        "bonus": {"agi": 10, "atk_speed": 8, "dodge": 3},
        "bonus_desc": "🏃 +10 Ловкость | ⚡ +8% Скор. атаки | 💨 +3% Уворот"
    },
    {
        "name": "Дагон I (Dagon I)",
        "icon": "⚡",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "rare",
        "bonus": {"int": 14, "spell_amp": 12, "burst_magic": 120},
        "bonus_desc": "🔮 +14 Интеллект | ✨ +12% Сила заклинаний | ⚡ Энерго-разряд 120 ед."
    },
    {
        "name": "Скипетр Эула (Eul's Scepter)",
        "icon": "🌪️",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "rare",
        "bonus": {"int": 18, "mp_regen": 5.0, "dodge": 8},
        "bonus_desc": "🔮 +18 Интеллект | 💧 +5 MP/сек | 💨 +8% Уворот | 🌪️ Циклон неуязвимости"
    },
    {
        "name": "Мистический Посох (Mystic Staff)",
        "icon": "🧙",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 28,
        "base_max": 42,
        "bonus": {"int": 25, "mp": 250, "spell_amp": 10},
        "bonus_desc": "🔮 +25 Интеллект | 💧 +250 MP | ✨ +10% Сила заклинаний"
    },
    {
        "name": "Орлиный Рог (Eaglehorn)",
        "icon": "🏹",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "base_min": 30,
        "base_max": 44,
        "bonus": {"agi": 25, "atk_speed": 18, "dodge": 6},
        "bonus_desc": "🏃 +25 Ловкость | ⚡ +18% Скор. атаки | 💨 +6% Уворот"
    },
    {
        "name": "Ботинки Путешествий (Boots of Travel)",
        "icon": "👟",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "rare",
        "bonus": {"agi": 15, "dodge": 12, "atk_speed": 15},
        "bonus_desc": "🏃 +15 Ловкость | 💨 +12% Уворот | ⚡ +15% Скор. атаки"
    },
    {
        "name": "Дагон III (Dagon III)",
        "icon": "⚡",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "epic",
        "bonus": {"int": 24, "spell_amp": 20, "burst_magic": 240},
        "bonus_desc": "🔮 +24 Интеллект | ✨ +20% Сила заклинаний | ⚡ Энерго-разряд 240 ед."
    },
    {
        "name": "Дагон V (Dagon V)",
        "icon": "⚡",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "epic",
        "bonus": {"int": 34, "spell_amp": 28, "burst_magic": 360},
        "bonus_desc": "🔮 +34 Интеллект | ✨ +28% Сила заклинаний | ⚡ Сокрушительный разряд 360 ед."
    },
    {
        "name": "Эфирный Клинок (Ethereal Blade)",
        "icon": "🪄",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 46,
        "base_max": 70,
        "bonus": {"int": 30, "agi": 20, "spell_amp": 22, "burst_magic": 180},
        "bonus_desc": "🔮 +30 Интеллект | 🏃 +20 Ловкость | ✨ +22% Сила магии | 🌀 Эфирный залп"
    },
    {
        "name": "Кайя и Саша (Kaya and Sange)",
        "icon": "⚔️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 44,
        "base_max": 66,
        "bonus": {"int": 20, "str": 20, "hp": 220, "spell_amp": 18, "lifesteal": 10},
        "bonus_desc": "🔮 +20 Интеллект | 💪 +20 Сила | ❤️ +220 HP | ✨ +18% Сила заклинаний | 🧛 +10% Вампиризм"
    },
    {
        "name": "Яша и Кайя (Yasha and Kaya)",
        "icon": "⚔️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 44,
        "base_max": 66,
        "bonus": {"int": 20, "agi": 20, "spell_amp": 18, "atk_speed": 22, "dodge": 10},
        "bonus_desc": "🔮 +20 Интеллект | 🏃 +20 Ловкость | ✨ +18% Сила заклинаний | ⚡ +22% Скор. атаки"
    },
    {
        "name": "Манта Стайл (Manta Style)",
        "icon": "👥",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 42,
        "base_max": 64,
        "bonus": {"agi": 26, "str": 10, "int": 10, "atk_speed": 25, "dodge": 12},
        "bonus_desc": "🏃 +26 Ловкость | 👑 +10 Сила/Инт | ⚡ +25% Скор. атаки | 💨 +12% Уворот | 👥 Призыв иллюзий"
    },
    {
        "name": "Серебряный Кортик (Silver Edge)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 62,
        "base_max": 92,
        "bonus": {"agi": 26, "crit": 28, "dodge": 15, "atk": 25},
        "bonus_desc": "🏃 +26 Ловкость | 💥 +28% Крит | 💨 +15% Уворот | ⚔️ +25 Базовый урон"
    },
    {
        "name": "Ураганная Пика (Hurricane Pike)",
        "icon": "🔱",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "base_min": 46,
        "base_max": 68,
        "bonus": {"agi": 22, "int": 18, "str": 15, "hp": 240, "dodge": 8},
        "bonus_desc": "🏃 +22 Ловкость | 🔮 +18 Интеллект | 💪 +15 Сила | ❤️ +240 HP"
    },
    {
        "name": "Сфера Линки (Linken's Sphere)",
        "icon": "🌐",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "bonus": {"all_stats": 22, "hp": 400, "mp": 400, "hp_regen": 8, "mp_regen": 6, "magic_immune": 1},
        "bonus_desc": "🌟 +22 Все характеристики | ❤️ +400 HP | 💧 +400 MP | 🛡️ Блок смертельного удара"
    }
]

DOTA_ITEMS_CATALOG = NATAR_ITEMS_CATALOG

DOTA_ITEMS_CATALOG = NATAR_ITEMS_CATALOG
