from typing import List, Dict, Any
from backend.db.crud.rpg.items_catalog import NATAR_ITEMS_CATALOG

NATAR_SHOP_CATALOG = [
    # --- НОВЫЕ АКТИВНЫЕ И ПАССИВНЫЕ АРТЕФАКТЫ DOTA 2 ---
    {
        "id": "shop_w_abyssal",
        "name": "Клинок Бездны (Abyssal Blade)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 4200,
        "price_gems": 12,
        "base_min": 75,
        "base_max": 110,
        "bonus": {"str": 25, "hp": 450, "dmg": 60, "abyssal_stun": 1, "bash": 25},
        "bonus_desc": "⚔️ +75..110 Урон | 🥩 +25 Сила | ❤️ +450 HP | ⚡ 25% Баш | 🌀 Активка: Стан на 2.5с"
    },
    {
        "id": "shop_r_hex",
        "name": "Коса Вайса (Scythe of Vyse / Хекс)",
        "icon": "🐑",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "price_gold": 4400,
        "price_gems": 14,
        "bonus": {"int": 35, "str": 12, "agi": 12, "mp_regen": 9, "spell_amp": 28, "hex": 1},
        "bonus_desc": "🔮 +35 Интеллект | 🌟 +12 Сила/Ловкость | 💧 +9 MP/сек | 🐑 Активка: Хекс (превращение в свинку на 3.5с)"
    },
    {
        "id": "shop_w_bloodthorn",
        "name": "Кровавый Шип (Bloodthorn)",
        "icon": "🌹",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 4500,
        "price_gems": 15,
        "base_min": 70,
        "base_max": 95,
        "bonus": {"int": 30, "atk_speed": 40, "spell_amp": 25, "bloodthorn_silence": 1},
        "bonus_desc": "⚔️ +70..95 Урон | 🔮 +30 Интеллект | ⚡ +40% Скор. атаки | 🩸 Активка: Безмолвие + 100% криты"
    },
    {
        "id": "shop_r_gleipnir",
        "name": "Глейпнир (Gleipnir)",
        "icon": "⛓️",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "price_gold": 4300,
        "price_gems": 12,
        "bonus": {"int": 24, "str": 14, "agi": 14, "lightning": 160, "gleipnir_root": 1},
        "bonus_desc": "🌟 +14..24 Характеристики | ⚡ Цепная молния 160 | ⛓️ Активка: Корни всей арены на 2.5с"
    },
    {
        "id": "shop_a_blademail",
        "name": "Шипастый Доспех (Blade Mail)",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "rare",
        "price_gold": 1800,
        "price_gems": 0,
        "defense": 16,
        "hp_bonus": 220,
        "bonus": {"atk": 28, "reflect": 100, "active_blademail": 1},
        "bonus_desc": "🛡️ +16 Броня | ❤️ +220 HP | ⚔️ +28 Урон | 🪞 Активка: Возвратка 100% входящего урона"
    },
    {
        "id": "shop_a_crimson",
        "name": "Багровая Защита (Crimson Guard)",
        "icon": "🔴",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "epic",
        "price_gold": 3200,
        "price_gems": 6,
        "defense": 22,
        "hp_bonus": 480,
        "bonus": {"str": 25, "hp_regen": 12, "damage_block": 85, "active_crimson": 1},
        "bonus_desc": "🛡️ +22 Броня | ❤️ +480 HP | 🥩 +25 Сила | 🔴 Активка: Купол блока 85 урона от каждой атаки"
    },
    {
        "id": "shop_r_pipe",
        "name": "Трубка Прозрения (Pipe of Insight)",
        "icon": "📯",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "epic",
        "price_gold": 3100,
        "price_gems": 5,
        "bonus": {"magic_resist": 30, "hp_regen": 10, "magic_shield": 650, "active_pipe": 1},
        "bonus_desc": "🔮 +30% Защита от магии | 💖 +10 HP/сек | 🛡️ Активка: Магический щит на 650 HP"
    },
    {
        "id": "shop_a_armlet",
        "name": "Арматура Мордиггиана (Armlet)",
        "icon": "🧤",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "rare",
        "price_gold": 2200,
        "price_gems": 0,
        "defense": 15,
        "hp_bonus": 280,
        "bonus": {"str": 15, "atk": 35, "unholy_strength": 1},
        "bonus_desc": "🛡️ +15 Броня | 🥩 +15 Сила | ⚔️ +35 Урон | 😈 Активка: Нечестивая сила (+40 Сила, +65 Урон)"
    },
    {
        "id": "shop_w_pike",
        "name": "Пика Урагана (Hurricane Pike)",
        "icon": "🔱",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "price_gold": 3400,
        "price_gems": 8,
        "base_min": 45,
        "base_max": 65,
        "bonus": {"agi": 24, "int": 18, "hp": 300, "active_pike": 1},
        "bonus_desc": "⚔️ +45..65 Урон | 🏃 +24 Ловкость | 🔮 +18 Интеллект | 💨 Активка: Отталкивание врагов на 130px"
    },
    {
        "id": "shop_w_silver",
        "name": "Серебряный Клинок (Silver Edge)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 4600,
        "price_gems": 16,
        "base_min": 68,
        "base_max": 92,
        "bonus": {"agi": 30, "atk_speed": 35, "crit": 25, "active_invis": 1},
        "bonus_desc": "⚔️ +68..92 Урон | 🏃 +30 Ловкость | ⚡ +35% Скорость | 👻 Активка: Теневой шаг + 250% крит из инвиза"
    },
    {
        "id": "shop_w_daedalus",
        "name": "Даэдалус (Daedalus)",
        "icon": "🏹",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 4300,
        "price_gems": 14,
        "base_min": 88,
        "base_max": 120,
        "bonus": {"crit_chance": 30, "crit_multiplier": 2.25},
        "bonus_desc": "⚔️ +88..120 Урон | 🎯 30% Шанс критического удара 225% урона"
    },
    {
        "id": "shop_w_bf",
        "name": "Боевой Топор (Battle Fury)",
        "icon": "🪓",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "legendary",
        "price_gold": 3800,
        "price_gems": 10,
        "base_min": 65,
        "base_max": 90,
        "bonus": {"hp_regen": 8, "mp_regen": 5, "cleave": 65},
        "bonus_desc": "⚔️ +65..90 Урон | 💖 +8 HP/сек | 🪓 65% Клив-урон по всем монстрам в радиусе"
    },
    {
        "id": "shop_w_radiance",
        "name": "Сияние (Radiance)",
        "icon": "☀️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 4800,
        "price_gems": 18,
        "base_min": 65,
        "base_max": 95,
        "bonus": {"radiance_burn": 60, "miss_aura": 17},
        "bonus_desc": "⚔️ +65..95 Урон | 🔥 Пылающая аура: 60 маг. урона/сек всей арене | 💨 Враги мажут на 17%"
    },
    {
        "id": "shop_w_desolator",
        "name": "Опустошитель (Desolator)",
        "icon": "🩸",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "legendary",
        "price_gold": 3500,
        "price_gems": 8,
        "base_min": 60,
        "base_max": 85,
        "bonus": {"minus_armor": 8},
        "bonus_desc": "⚔️ +60..85 Урон | 🩸 Коррозия: -8 брони врагам при ударах"
    },
    {
        "id": "shop_w_mkb",
        "name": "Посох Короля Обезьян (Monkey King Bar)",
        "icon": "🥢",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 4400,
        "price_gems": 14,
        "base_min": 55,
        "base_max": 80,
        "bonus": {"atk_speed": 35, "true_strike": 1, "pure_bonus": 75},
        "bonus_desc": "⚔️ +55..80 Урон | ⚡ +35% Скорость | 🎯 True Strike (удары без промахов) | 💥 +75 Чистый урон"
    },
    {
        "id": "shop_r_skadi",
        "name": "Око Скади (Eye of Skadi)",
        "icon": "❄️",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "price_gold": 4600,
        "price_gems": 15,
        "bonus": {"all_stats": 25, "hp": 550, "mp": 550, "frost_slow": 45},
        "bonus_desc": "🌟 +25 Все характеристики | ❤️ +550 HP | 💧 +550 MP | ❄️ Ледяной удар: -45% скорости врагов"
    },
    {
        "id": "shop_a_tarasque",
        "name": "Сердце Тарраски (Heart of Tarrasque)",
        "icon": "❤️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "immortal",
        "price_gold": 4500,
        "price_gems": 15,
        "defense": 25,
        "hp_bonus": 850,
        "bonus": {"str": 45, "pct_hp_regen": 2.5},
        "bonus_desc": "🛡️ +25 Броня | ❤️ +850 HP | 🥩 +45 Сила | 💖 Регенерация +2.5% от макс. HP в секунду"
    },
    {
        "id": "shop_r_bloodstone",
        "name": "Кровавый Камень (Bloodstone)",
        "icon": "🩸",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "price_gold": 4400,
        "price_gems": 14,
        "bonus": {"hp": 600, "mp": 600, "spell_amp": 30, "spell_lifesteal": 30},
        "bonus_desc": "❤️ +600 HP | 💧 +600 MP | ✨ +30% Сила заклинаний | 🩸 30% Магический вампиризм от скиллов"
    },
    {
        "id": "shop_w_butterfly",
        "name": "Бабочка (Butterfly)",
        "icon": "🦋",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 4700,
        "price_gems": 16,
        "base_min": 50,
        "base_max": 75,
        "bonus": {"agi": 35, "dodge": 35, "atk_speed": 35},
        "bonus_desc": "⚔️ +50..75 Урон | 🏃 +35 Ловкость | 💨 +35% Уворот от ударов | ⚡ +35% Скорость атаки"
    },
    {
        "id": "shop_w_rapier",
        "name": "Божественная Рапира (Divine Rapier)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 9000,
        "price_gems": 40,
        "base_min": 400,
        "base_max": 550,
        "bonus": {"true_strike": 1},
        "bonus_desc": "⚔️ +400..550 Колоссальный урон | 🎯 True Strike — абсолютное оружие богов"
    },

    # --- MAGE SHOP ARTIFACTS (ИНТЕЛЛЕКТ И СИЛА ЗАКЛИНАНИЙ) ---
    {
        "id": "shop_w_kaya",
        "name": "Кайя (Kaya)",
        "icon": "🪄",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "price_gold": 1400,
        "price_gems": 0,
        "base_min": 22,
        "base_max": 34,
        "bonus": {"int": 16, "mp": 150, "spell_amp": 12},
        "bonus_desc": "🔮 +16 Интеллект | 💧 +150 MP | ✨ +12% Сила заклинаний"
    },
    {
        "id": "shop_r_aether_lens",
        "name": "Линза Эфира (Aether Lens)",
        "icon": "🔮",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "rare",
        "price_gold": 1600,
        "price_gems": 0,
        "bonus": {"int": 15, "mp": 350, "spell_amp": 14},
        "bonus_desc": "🔮 +15 Интеллект | 💧 +350 MP | ✨ +14% Сила заклинаний"
    },
    {
        "id": "shop_r_dagon",
        "name": "Дагон I (Dagon I)",
        "icon": "⚡",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "rare",
        "price_gold": 1800,
        "price_gems": 0,
        "bonus": {"int": 16, "spell_amp": 15, "burst_magic": 150},
        "bonus_desc": "🔮 +16 Интеллект | ✨ +15% Сила заклинаний | ⚡ Энерго-разряд 150 ед."
    },
    {
        "id": "shop_r_eul",
        "name": "Скипетр Эула (Eul's Scepter)",
        "icon": "🌪️",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "rare",
        "price_gold": 1500,
        "price_gems": 0,
        "bonus": {"int": 18, "mp_regen": 6.0, "dodge": 8},
        "bonus_desc": "🔮 +18 Интеллект | 💧 +6 MP/сек | 💨 +8% Уворот"
    },
    {
        "id": "shop_r_shard",
        "name": "Осколок Аганима (Aghanim Shard)",
        "icon": "🔷",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "rare",
        "price_gold": 2200,
        "price_gems": 10,
        "bonus": {"all_stats": 10, "ult_boost": 25, "ult_cd": 15, "spell_amp": 10},
        "bonus_desc": "👑 +10 Все характеристики | 💥 +25% Урон Ульты | ⏱️ -15% КД Ульты"
    },
    {
        "id": "shop_r_octarine",
        "name": "Октариновое Ядро (Octarine Core)",
        "icon": "💎",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "epic",
        "price_gold": 3200,
        "price_gems": 25,
        "bonus": {"hp": 450, "mp": 750, "cooldown_reduct": 25, "spell_amp": 18, "int": 20},
        "bonus_desc": "❤️ +450 HP | 💧 +750 MP | ⏱️ -25% КД | 🔮 +20 Интеллект"
    },
    {
        "id": "shop_a_shiva",
        "name": "Страж Шивы (Shiva's Guard)",
        "icon": "❄️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "epic",
        "price_gold": 3100,
        "price_gems": 20,
        "base_def": 22,
        "base_hp": 300,
        "bonus": {"int": 35, "slow_aura": 30},
        "bonus_desc": "🛡️ +22 Броня | 🔮 +35 Интеллект | ❄️ Ледяное кольцо замедления"
    },

    # --- AGILITY SHOP ARTIFACTS (ЛОВКОСТЬ И СКОРОСТЬ) ---
    {
        "id": "shop_w_yasha",
        "name": "Яша (Yasha)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "price_gold": 1400,
        "price_gems": 0,
        "base_min": 24,
        "base_max": 36,
        "bonus": {"agi": 18, "atk_speed": 16, "dodge": 8},
        "bonus_desc": "🏃 +18 Ловкость | ⚡ +16% Скор. атаки | 💨 +8% Уворот"
    },
    {
        "id": "shop_w_diffusal",
        "name": "Диффуза (Diffusal Blade)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "price_gold": 1750,
        "price_gems": 0,
        "base_min": 28,
        "base_max": 42,
        "bonus": {"agi": 18, "mana_burn": 35},
        "bonus_desc": "🏃 +18 Ловкость | 💧 Сожжение 35 маны за удар"
    },
    {
        "id": "shop_w_butterfly",
        "name": "Бабочка (Butterfly)",
        "icon": "🦋",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "price_gold": 3400,
        "price_gems": 25,
        "base_min": 48,
        "base_max": 72,
        "bonus": {"agi": 40, "dodge": 35, "atk": 30},
        "bonus_desc": "🏃 +40 Ловкость | 💨 +35% Уворот | ⚔️ +30 Базовый урон"
    },
    {
        "id": "shop_w_manta",
        "name": "Манта Стайл (Manta Style)",
        "icon": "👥",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "price_gold": 3200,
        "price_gems": 20,
        "base_min": 44,
        "base_max": 66,
        "bonus": {"agi": 26, "str": 10, "int": 10, "atk_speed": 25, "dodge": 12},
        "bonus_desc": "🏃 +26 Ловкость | 👑 +10 Сила/Инт | ⚡ +25% Скор. атаки | 👥 Иллюзии"
    },
    {
        "id": "shop_w_daedalus",
        "name": "Дедал (Daedalus)",
        "icon": "🏹",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "epic",
        "price_gold": 3300,
        "price_gems": 20,
        "base_min": 85,
        "base_max": 125,
        "bonus": {"crit": 30},
        "bonus_desc": "⚔️ +85..125 Урон | 💥 +30% Шанс Крита (x2.25)"
    },

    # --- STRENGTH & DEFENSE SHOP ARTIFACTS (СИЛА И БРОНЯ) ---
    {
        "id": "shop_w_sange",
        "name": "Саша (Sange)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "rare",
        "price_gold": 1400,
        "price_gems": 0,
        "base_min": 24,
        "base_max": 36,
        "bonus": {"str": 18, "hp": 200, "lifesteal": 8},
        "bonus_desc": "💪 +18 Сила | ❤️ +200 HP | 🧛 +8% Вампиризм"
    },
    {
        "id": "shop_a_blade_mail",
        "name": "Возвратный Доспех (Blade Mail)",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "rare",
        "price_gold": 1200,
        "price_gems": 0,
        "base_def": 10,
        "base_hp": 130,
        "bonus": {"reflect": 30, "atk": 16},
        "bonus_desc": "🛡️ +10 Броня | ⚔️ +16 Урон | 🦔 Отражение 30%"
    },
    {
        "id": "shop_a_heart_tarrasque",
        "name": "Сердце Тарраска (Heart of Tarrasque)",
        "icon": "❤️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "epic",
        "price_gold": 3300,
        "price_gems": 25,
        "base_def": 12,
        "base_hp": 750,
        "bonus": {"str": 45, "hp_regen_pct": 2},
        "bonus_desc": "💪 +45 Сила | ❤️ +750 HP | 💚 +2% Макс. HP/сек"
    },
    {
        "id": "shop_a_assault_cuirass",
        "name": "Кираса Штурма (Assault Cuirass)",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "epic",
        "price_gold": 2900,
        "price_gems": 20,
        "base_def": 24,
        "base_hp": 200,
        "bonus": {"atk_speed": 35, "aura_armor": 6},
        "bonus_desc": "🛡️ +24 Броня | ⚡ +35% Скор. атаки | 🛡️ +6 Аура брони"
    },
    {
        "id": "shop_a_forged_cuirass",
        "name": "Кованая Кираса Стража",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "rare",
        "price_gold": 650,
        "price_gems": 4,
        "base_def": 14,
        "base_hp": 120,
        "bonus": {"defense": 5, "hp": 80},
        "bonus_desc": "🛡️ +14 Броня | ❤️ +120 HP"
    },
    {
        "id": "shop_r_blink_dagger",
        "name": "Кинжал Скачка (Blink Dagger)",
        "icon": "🗡️",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "rare",
        "price_gold": 1100,
        "price_gems": 8,
        "bonus": {"dodge": 12, "atk_speed": 10},
        "bonus_desc": "💨 +12% Уворот | ⚡ +10% Скор. атаки | ⚡ Мгновенный скачок"
    },
    {
        "id": "shop_r_satanic",
        "name": "Сатаник (Satanic)",
        "icon": "🩸",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "immortal",
        "price_gold": 4200,
        "price_gems": 18,
        "bonus": {"str": 35, "hp": 500, "lifesteal": 30},
        "bonus_desc": "🥩 +35 Сила | ❤️ +500 HP | 🧛 +30% Вампиризм ото всех атак"
    },
    {
        "id": "shop_w_mjollnir",
        "name": "Мьёльнир (Mjollnir)",
        "icon": "⚡",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 4600,
        "price_gems": 16,
        "base_min": 65,
        "base_max": 90,
        "bonus": {"atk_speed": 40, "lightning_proc": 220},
        "bonus_desc": "⚔️ +65..90 Урон | ⚡ +40% Скор. атаки | ⚡ 25% Шанс вызова цепной молнии на 220 урона"
    },
    {
        "id": "shop_w_khanda",
        "name": "Кханда (Khanda)",
        "icon": "🗡️",
        "type": "weapon",
        "slot": "weapon",
        "slot_name": "Оружие",
        "slot_icon": "⚔️",
        "rarity": "immortal",
        "price_gold": 4500,
        "price_gems": 15,
        "base_min": 60,
        "base_max": 85,
        "bonus": {"hp": 350, "mp": 300, "crit": 20, "empower_spell": 150},
        "bonus_desc": "⚔️ +60..85 Урон | ❤️ +350 HP | 💧 +300 MP | 💥 Заклинания наносят +150 критического физ. урона"
    },
    {
        "id": "shop_r_moon_shard",
        "name": "Осколок Луны (Moon Shard)",
        "icon": "🌙",
        "type": "relic",
        "slot": "relic",
        "slot_name": "Реликвия",
        "slot_icon": "💍",
        "rarity": "legendary",
        "price_gold": 3800,
        "price_gems": 12,
        "bonus": {"atk_speed": 60, "night_vision": 1},
        "bonus_desc": "⚡ +60% Скорость атаки | 🌙 Ночное зрение сквозь туман войны"
    },
    {
        "id": "shop_a_vanguard",
        "name": "Авангард (Vanguard)",
        "icon": "🛡️",
        "type": "armor",
        "slot": "armor",
        "slot_name": "Броня",
        "slot_icon": "🛡️",
        "rarity": "rare",
        "price_gold": 1900,
        "price_gems": 0,
        "base_def": 12,
        "base_hp": 350,
        "bonus": {"hp_regen": 7, "damage_block": 70},
        "bonus_desc": "🛡️ +12 Броня | ❤️ +350 HP | 🩹 +7 HP/сек | 🛡️ 70% Шанс заблокировать 70 урона"
    },

    # --- CONSUMABLES (ЗЕЛЬЯ) ---
    {
        "id": "shop_p_healing",
        "name": "Зелье Исцеления",
        "icon": "🧴",
        "type": "potion",
        "slot": "consumable",
        "slot_name": "Зелье",
        "slot_icon": "🧪",
        "rarity": "common",
        "price_gold": 50,
        "price_gems": 0,
        "heal_amount": 120,
        "count": 3,
        "bonus_desc": "❤️ Восстанавливает 120 HP (3 шт.)"
    },
    {
        "id": "shop_p_mana",
        "name": "Эликсир Маны",
        "icon": "🧪",
        "type": "potion",
        "slot": "consumable",
        "slot_name": "Зелье",
        "slot_icon": "🧪",
        "rarity": "common",
        "price_gold": 40,
        "price_gems": 0,
        "mp_amount": 150,
        "count": 3,
        "bonus_desc": "🔮 Восстанавливает 150 MP (3 шт.)"
    },
    {
        "id": "shop_p_cheese",
        "name": "Сыр Силы Катакомб",
        "icon": "🧀",
        "type": "potion",
        "slot": "consumable",
        "slot_name": "Зелье",
        "slot_icon": "🧪",
        "rarity": "immortal",
        "price_gold": 450,
        "price_gems": 5,
        "heal_amount": 600,
        "mp_amount": 450,
        "count": 1,
        "bonus_desc": "👑 Восстанавливает 600 HP и 450 MP!"
    }
]

# Sync unique shop items into NATAR_ITEMS_CATALOG so reward chests and drops also contain them
_existing_item_names = {it.get("name") for it in NATAR_ITEMS_CATALOG}
for _shop_it in NATAR_SHOP_CATALOG:
    if _shop_it.get("type") in ("weapon", "armor", "relic") and _shop_it.get("name") not in _existing_item_names:
        _existing_item_names.add(_shop_it.get("name"))
        NATAR_ITEMS_CATALOG.append(dict(_shop_it))

