// ============================================================
// 11_admin_catalog_data.js — Встроенный каталог предметов RPG
// 148 предметов для мгновенной доступности без задержек сети
// ============================================================
window._DEFAULT_RPG_CATALOG = [
  {"name": "Железная Ветка (Iron Branch)", "icon": "🌿", "rarity": "common", "slot": "relic"},
  {"name": "Перчатки Силы (Gauntlets of Strength)", "icon": "🥊", "rarity": "common", "slot": "relic"},
  {"name": "Тапочки Ловкости (Slippers of Agility)", "icon": "🥿", "rarity": "common", "slot": "relic"},
  {"name": "Мантия Интеллекта (Mantle of Intelligence)", "icon": "📜", "rarity": "common", "slot": "relic"},
  {"name": "Венец Благородства (Circlet)", "icon": "👑", "rarity": "common", "slot": "relic"},
  {"name": "Топорик Лесоруба (Quelling Blade)", "icon": "🪓", "rarity": "common", "slot": "weapon"},
  {"name": "Прочный Щиток (Stout Shield)", "icon": "🛡️", "rarity": "common", "slot": "armor"},
  {"name": "Кольцо Защиты (Ring of Protection)", "icon": "💍", "rarity": "common", "slot": "armor"},
  {"name": "Волшебная Палочка (Magic Stick)", "icon": "🪄", "rarity": "common", "slot": "relic"},
  {"name": "Камень Порчи (Blight Stone)", "icon": "🪨", "rarity": "common", "slot": "weapon"},
  {"name": "Шнурок Ветра (Wind Lace)", "icon": "👟", "rarity": "common", "slot": "armor"},
  {"name": "Капли Дождя (Infused Raindrops)", "icon": "💧", "rarity": "common", "slot": "relic"},
  {"name": "Ржавый Кинжал Новичка", "icon": "🗡️", "rarity": "common", "slot": "weapon"},
  {"name": "Тканевая Куртка Ополченца", "icon": "🥋", "rarity": "common", "slot": "armor"},
  {"name": "Кольцо Регенерации (Ring of Regen)", "icon": "💚", "rarity": "common", "slot": "relic"},
  {"name": "Дубовый Боевой Посох", "icon": "🪵", "rarity": "common", "slot": "weapon"},
  {"name": "Клинки Атаки (Blades of Attack)", "icon": "⚔️", "rarity": "uncommon", "slot": "weapon"},
  {"name": "Кольчуга (Chainmail)", "icon": "🦺", "rarity": "uncommon", "slot": "armor"},
  {"name": "Шлем Железной Воли (Helm of Iron Will)", "icon": "🪖", "rarity": "uncommon", "slot": "armor"},
  {"name": "Маска Смерти (Morbid Mask)", "icon": "🎭", "rarity": "uncommon", "slot": "relic"},
  {"name": "Сапоги Скорости (Boots of Speed)", "icon": "👢", "rarity": "uncommon", "slot": "armor"},
  {"name": "Фазовые Сапоги (Phase Boots)", "icon": "👢", "rarity": "uncommon", "slot": "armor"},
  {"name": "Сапоги Мощи (Power Treads)", "icon": "🥾", "rarity": "uncommon", "slot": "armor"},
  {"name": "Сфера Коррозии (Orb of Corrosion)", "icon": "🧪", "rarity": "uncommon", "slot": "weapon"},
  {"name": "Клинок Сокола (Falcon Blade)", "icon": "🪶", "rarity": "uncommon", "slot": "weapon"},
  {"name": "Авангард (Vanguard)", "icon": "🛡️", "rarity": "uncommon", "slot": "armor"},
  {"name": "Урна Теней (Urn of Shadows)", "icon": "🏺", "rarity": "uncommon", "slot": "relic"},
  {"name": "Медальон Мужества (Medallion of Courage)", "icon": "🏅", "rarity": "uncommon", "slot": "armor"},
  {"name": "Корона Императора (Crown)", "icon": "👑", "rarity": "uncommon", "slot": "relic"},
  {"name": "Пояс Великана (Belt of Strength)", "icon": "🥋", "rarity": "uncommon", "slot": "armor"},
  {"name": "Сапоги Эльфийской Ловкости (Boots of Elvenskin)", "icon": "🥿", "rarity": "uncommon", "slot": "armor"},
  {"name": "Мантия Мага (Robe of the Magi)", "icon": "👘", "rarity": "uncommon", "slot": "armor"},
  {"name": "Палаш (Broadsword)", "icon": "🗡️", "rarity": "rare", "slot": "weapon"},
  {"name": "Клеймор (Claymore)", "icon": "🗡️", "rarity": "rare", "slot": "weapon"},
  {"name": "Мифриловый Молот (Mithril Hammer)", "icon": "🔨", "rarity": "rare", "slot": "weapon"},
  {"name": "Латный Доспех (Platemail)", "icon": "🛡️", "rarity": "rare", "slot": "armor"},
  {"name": "Кристалис (Crystalys)", "icon": "💎", "rarity": "rare", "slot": "weapon"},
  {"name": "Крушитель Черепов (Skull Basher)", "icon": "🔨", "rarity": "rare", "slot": "weapon"},
  {"name": "Теневой Клинок (Shadow Blade)", "icon": "🗡️", "rarity": "rare", "slot": "weapon"},
  {"name": "Яша (Yasha)", "icon": "🗡️", "rarity": "rare", "slot": "weapon"},
  {"name": "Саша (Sange)", "icon": "🗡️", "rarity": "rare", "slot": "weapon"},
  {"name": "Кайя (Kaya)", "icon": "🪄", "rarity": "rare", "slot": "weapon"},
  {"name": "Молния (Maelstrom)", "icon": "⚡", "rarity": "rare", "slot": "weapon"},
  {"name": "Клинок Очищения (Diffusal Blade)", "icon": "🗡️", "rarity": "rare", "slot": "weapon"},
  {"name": "Пика Дракона (Dragon Lance)", "icon": "🔱", "rarity": "rare", "slot": "weapon"},
  {"name": "Возвратный Доспех (Blade Mail)", "icon": "🛡️", "rarity": "rare", "slot": "armor"},
  {"name": "Аганимный Осколок (Aghanim Shard)", "icon": "🔷", "rarity": "rare", "slot": "relic"},
  {"name": "Саша и Яша (Sange and Yasha)", "icon": "⚔️", "rarity": "rare", "slot": "weapon"},
  {"name": "Боевой Топор (Battle Fury)", "icon": "🪓", "rarity": "epic", "slot": "weapon"},
  {"name": "Дедал (Daedalus)", "icon": "🏹", "rarity": "epic", "slot": "weapon"},
  {"name": "Бабочка (Butterfly)", "icon": "🦋", "rarity": "epic", "slot": "weapon"},
  {"name": "Обезьяний Посох (Monkey King Bar)", "icon": "🐒", "rarity": "epic", "slot": "weapon"},
  {"name": "Сияние (Radiance)", "icon": "☀️", "rarity": "epic", "slot": "weapon"},
  {"name": "Опустошитель (Desolator)", "icon": "🔴", "rarity": "epic", "slot": "weapon"},
  {"name": "Сатаник (Satanic)", "icon": "🩸", "rarity": "epic", "slot": "relic"},
  {"name": "Сердце Тарраска (Heart of Tarrasque)", "icon": "❤️", "rarity": "epic", "slot": "armor"},
  {"name": "Кираса Штурма (Assault Cuirass)", "icon": "🛡️", "rarity": "epic", "slot": "armor"},
  {"name": "Черный Королевский Бар (Black King Bar)", "icon": "🟡", "rarity": "epic", "slot": "relic"},
  {"name": "Страж Шивы (Shiva Guard)", "icon": "❄️", "rarity": "epic", "slot": "armor"},
  {"name": "Око Скади (Eye of Skadi)", "icon": "👁️", "rarity": "epic", "slot": "relic"},
  {"name": "Кровавый Шип (Bloodthorn)", "icon": "🌹", "rarity": "epic", "slot": "weapon"},
  {"name": "Мьёльнир (Mjollnir)", "icon": "⚡", "rarity": "epic", "slot": "weapon"},
  {"name": "Коса Вайса (Scythe of Vyse)", "icon": "🐏", "rarity": "epic", "slot": "relic"},
  {"name": "Абиссальный Клинок (Abyssal Blade)", "icon": "🗡️", "rarity": "epic", "slot": "weapon"},
  {"name": "Божественная Рапира (Divine Rapier)", "icon": "🗡️", "rarity": "immortal", "slot": "weapon"},
  {"name": "Эгида Бессмертия (Aegis of the Immortal)", "icon": "🛡️", "rarity": "immortal", "slot": "relic"},
  {"name": "Сыр Рошана (Cheese)", "icon": "🧀", "rarity": "immortal", "slot": "consumable"},
  {"name": "Благословение Аганима (Aghanim Blessing)", "icon": "🔮", "rarity": "immortal", "slot": "relic"},
  {"name": "Сфера Обновления (Refresher Orb)", "icon": "🟢", "rarity": "immortal", "slot": "relic"},
  {"name": "Апекс (Apex)", "icon": "🔺", "rarity": "immortal", "slot": "relic"},
  {"name": "Падшие Небеса (Fallen Sky)", "icon": "☄️", "rarity": "immortal", "slot": "weapon"},
  {"name": "Зеркальный Щит (Mirror Shield)", "icon": "🪞", "rarity": "immortal", "slot": "armor"},
  {"name": "Гигантское Кольцо (Giant Ring)", "icon": "💍", "rarity": "immortal", "slot": "armor"},
  {"name": "Стигийский Дезолятор (Stygian Desolator)", "icon": "🩸", "rarity": "immortal", "slot": "weapon"},
  {"name": "Око Вечности (Eye of Eternity)", "icon": "👁️", "rarity": "immortal", "slot": "relic"},
  {"name": "Дубовый Посох (Oak Staff)", "icon": "🦯", "rarity": "common", "slot": "weapon"},
  {"name": "Ржавый Кинжал (Rusty Dagger)", "icon": "🗡️", "rarity": "common", "slot": "weapon"},
  {"name": "Деревянный Баклер (Wooden Buckler)", "icon": "🛡️", "rarity": "common", "slot": "armor"},
  {"name": "Треснувший Опал (Cracked Opal)", "icon": "💎", "rarity": "common", "slot": "relic"},
  {"name": "Кольцо Базилиуса (Ring of Basilius)", "icon": "💍", "rarity": "common", "slot": "relic"},
  {"name": "Топорик Лесоруба (Woodcutter Hatchet)", "icon": "🪓", "rarity": "common", "slot": "weapon"},
  {"name": "Повязка Ученика (Apprentice Band)", "icon": "🎗️", "rarity": "common", "slot": "armor"},
  {"name": "Шнурок Проворства (Lace of Haste)", "icon": "🎗️", "rarity": "common", "slot": "relic"},
  {"name": "Брейсер Защитника (Bracer)", "icon": "🥊", "rarity": "uncommon", "slot": "relic"},
  {"name": "Врейс Бенд (Wraith Band)", "icon": "💍", "rarity": "uncommon", "slot": "relic"},
  {"name": "Нулл Талисман (Null Talisman)", "icon": "📿", "rarity": "uncommon", "slot": "relic"},
  {"name": "Кольцо Души (Soul Ring)", "icon": "💍", "rarity": "uncommon", "slot": "relic"},
  {"name": "Капля Жизни (Tear of Life)", "icon": "💧", "rarity": "uncommon", "slot": "relic"},
  {"name": "Плащ Мудрости (Cloak of Wisdom)", "icon": "🧥", "rarity": "uncommon", "slot": "armor"},
  {"name": "Кинжал Тени (Shadow Dagger)", "icon": "🗡️", "rarity": "uncommon", "slot": "weapon"},
  {"name": "Кольцо Аквилы (Ring of Aquila)", "icon": "💍", "rarity": "uncommon", "slot": "relic"},
  {"name": "Барабаны Войны (Drum of Endurance)", "icon": "🥁", "rarity": "rare", "slot": "relic"},
  {"name": "Владимир (Vladmir Offering)", "icon": "🦇", "rarity": "rare", "slot": "relic"},
  {"name": "Солар Крест (Solar Crest)", "icon": "☀️", "rarity": "rare", "slot": "armor"},
  {"name": "Линза Эфира (Aether Lens)", "icon": "🔍", "rarity": "rare", "slot": "relic"},
  {"name": "Плащ Мерцания (Glimmer Cape)", "icon": "🧥", "rarity": "rare", "slot": "armor"},
  {"name": "Эхо Сабля (Echo Sabre)", "icon": "⚔️", "rarity": "rare", "slot": "weapon"},
  {"name": "Метеор Хаммер (Meteor Hammer)", "icon": "☄️", "rarity": "rare", "slot": "weapon"},
  {"name": "Меч Гарпуна (Harpoon Blade)", "icon": "🔱", "rarity": "rare", "slot": "weapon"},
  {"name": "Крикун Глейпнир (Gleipnir)", "icon": "⚡", "rarity": "epic", "slot": "weapon"},
  {"name": "Кримсон Гард (Crimson Guard)", "icon": "🛡️", "rarity": "epic", "slot": "armor"},
  {"name": "Трубка Прозрения (Pipe of Insight)", "icon": "🪈", "rarity": "epic", "slot": "armor"},
  {"name": "Эон Диск (Aeon Disk)", "icon": "📀", "rarity": "epic", "slot": "armor"},
  {"name": "Винд Вейкер (Wind Waker)", "icon": "🌪️", "rarity": "epic", "slot": "relic"},
  {"name": "Брошь Призрака (Revenant Brooch)", "icon": "👻", "rarity": "epic", "slot": "relic"},
  {"name": "Октарин Ядро (Octarine Core)", "icon": "🔮", "rarity": "epic", "slot": "relic"},
  {"name": "Сфера Линкена (Linken Sphere)", "icon": "🌐", "rarity": "epic", "slot": "relic"},
  {"name": "Книга Мертвых (Book of the Dead)", "icon": "📖", "rarity": "immortal", "slot": "relic"},
  {"name": "Пиратская Шляпа (Pirate Hat)", "icon": "🏴‍☠️", "rarity": "immortal", "slot": "armor"},
  {"name": "Сапоги Силы (Force Boots)", "icon": "👢", "rarity": "immortal", "slot": "armor"},
  {"name": "Камень Провидца (Seer Stone)", "icon": "🔮", "rarity": "immortal", "slot": "relic"},
  {"name": "Экс Махина (Ex Machina)", "icon": "⚙️", "rarity": "immortal", "slot": "armor"},
  {"name": "Посох Чародея (Staff of Wizardry)", "icon": "🪄", "rarity": "uncommon", "slot": "weapon"},
  {"name": "Клинок Ловкости (Blade of Alacrity)", "icon": "🗡️", "rarity": "uncommon", "slot": "weapon"},
  {"name": "Дагон I (Dagon I)", "icon": "⚡", "rarity": "rare", "slot": "relic"},
  {"name": "Скипетр Эула (Eul's Scepter)", "icon": "🌪️", "rarity": "rare", "slot": "relic"},
  {"name": "Мистический Посох (Mystic Staff)", "icon": "🧙", "rarity": "rare", "slot": "weapon"},
  {"name": "Орлиный Рог (Eaglehorn)", "icon": "🏹", "rarity": "rare", "slot": "weapon"},
  {"name": "Ботинки Путешествий (Boots of Travel)", "icon": "👟", "rarity": "rare", "slot": "relic"},
  {"name": "Дагон III (Dagon III)", "icon": "⚡", "rarity": "epic", "slot": "relic"},
  {"name": "Дагон V (Dagon V)", "icon": "⚡", "rarity": "epic", "slot": "relic"},
  {"name": "Эфирный Клинок (Ethereal Blade)", "icon": "🪄", "rarity": "epic", "slot": "weapon"},
  {"name": "Кайя и Саша (Kaya and Sange)", "icon": "⚔️", "rarity": "epic", "slot": "weapon"},
  {"name": "Яша и Кайя (Yasha and Kaya)", "icon": "⚔️", "rarity": "epic", "slot": "weapon"},
  {"name": "Манта Стайл (Manta Style)", "icon": "👥", "rarity": "epic", "slot": "weapon"},
  {"name": "Серебряный Кортик (Silver Edge)", "icon": "🗡️", "rarity": "epic", "slot": "weapon"},
  {"name": "Ураганная Пика (Hurricane Pike)", "icon": "🔱", "rarity": "epic", "slot": "weapon"},
  {"name": "Сфера Линки (Linken's Sphere)", "icon": "🌐", "rarity": "immortal", "slot": "relic"},
  {"name": "Клинок Бездны (Abyssal Blade)", "icon": "🗡️", "rarity": "immortal", "slot": "weapon"},
  {"name": "Коса Вайса (Scythe of Vyse / Хекс)", "icon": "🐑", "rarity": "immortal", "slot": "relic"},
  {"name": "Глейпнир (Gleipnir)", "icon": "⛓️", "rarity": "immortal", "slot": "relic"},
  {"name": "Шипастый Доспех (Blade Mail)", "icon": "🛡️", "rarity": "rare", "slot": "armor"},
  {"name": "Багровая Защита (Crimson Guard)", "icon": "🔴", "rarity": "epic", "slot": "armor"},
  {"name": "Арматура Мордиггиана (Armlet)", "icon": "🧤", "rarity": "rare", "slot": "armor"},
  {"name": "Пика Урагана (Hurricane Pike)", "icon": "🔱", "rarity": "epic", "slot": "weapon"},
  {"name": "Серебряный Клинок (Silver Edge)", "icon": "🗡️", "rarity": "immortal", "slot": "weapon"},
  {"name": "Даэдалус (Daedalus)", "icon": "🏹", "rarity": "immortal", "slot": "weapon"},
  {"name": "Посох Короля Обезьян (Monkey King Bar)", "icon": "🥢", "rarity": "immortal", "slot": "weapon"},
  {"name": "Сердце Тарраски (Heart of Tarrasque)", "icon": "❤️", "rarity": "immortal", "slot": "armor"},
  {"name": "Кровавый Камень (Bloodstone)", "icon": "🩸", "rarity": "immortal", "slot": "relic"},
  {"name": "Осколок Аганима (Aghanim Shard)", "icon": "🔷", "rarity": "rare", "slot": "relic"},
  {"name": "Октариновое Ядро (Octarine Core)", "icon": "💎", "rarity": "epic", "slot": "relic"},
  {"name": "Страж Шивы (Shiva's Guard)", "icon": "❄️", "rarity": "epic", "slot": "armor"},
  {"name": "Диффуза (Diffusal Blade)", "icon": "🗡️", "rarity": "rare", "slot": "weapon"},
  {"name": "Кованая Кираса Стража", "icon": "🛡️", "rarity": "rare", "slot": "armor"},
  {"name": "Кинжал Скачка (Blink Dagger)", "icon": "🗡️", "rarity": "rare", "slot": "relic"},
  {"name": "Кханда (Khanda)", "icon": "🗡️", "rarity": "immortal", "slot": "weapon"},
  {"name": "Осколок Луны (Moon Shard)", "icon": "🌙", "rarity": "legendary", "slot": "relic"},
];
