"""Centralized catalog for Natbirzha economic sabotages and crises."""

from typing import Any, Dict, Optional

SABOTAGES_CATALOG: Dict[str, Dict[str, Any]] = {
    "key_rate": {
        "id": "key_rate",
        "icon": "📈",
        "name": "Взлёт ключевой ставки",
        "duration_hours": 24,
        "description": "ЦБ резко поднимает ставку. Кредиты дорожают, облигации дешевеют, рынок акций проседает.",
        "one_time_stock_shock": -0.05,
        "credit_rate_delta": 0.10,
        "bond_price_mult": 0.90,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {},
        "other_income_mult": 0.90,
        "resource_multipliers": {},
        "news_headline": "⚡ ЦБ экстренно поднял ключевую ставку!",
        "news_body": "Кредиты стали дороже на +10%, гособлигации просели на 10%, акции публичных компаний упали на 5%. Все предприятия теряют 10% дохода — деньги стали дорогими.",
        "end_headline": "✅ Ключевая ставка возвращена к базовому значению",
        "end_body": "Ставки по кредитам и доходность гособлигаций вернулись в штатный режим. Доходы предприятий нормализованы.",
    },
    "military_operation": {
        "id": "military_operation",
        "icon": "🪖",
        "name": "Специальная военная операция",
        "duration_hours": 12,
        "description": "Военное положение. Спрос на топливо и энергию зашкаливает, логистические цепочки нарушены, фондовый рынок в панике.",
        "one_time_stock_shock": -0.15,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "oilman": 1.20,
            "power_engineer": 1.10,
            "logistics": 0.75,
        },
        "other_income_mult": 0.85,
        "resource_multipliers": {
            "fuel_diesel": 1.25,
            "gasoline": 1.25,
            "jet_fuel": 1.25,
            "oil_crude": 1.25,
            "gas_natural": 1.25,
        },
        "news_headline": "🪖 Объявлено особое положение!",
        "news_body": "Спрос на топливо и энергетику вырос (+25% к цене топлива). Все предприятия теряют 15% дохода от военных издержек. Логистика несет тяжелые потери (-25%). Акции упали на 15%.",
        "end_headline": "🕊️ Особое положение завершено",
        "end_body": "Топливный рынок и логистические цепочки стабилизировались. Доходы отраслей вернулись в норму.",
    },
    "state_default": {
        "id": "state_default",
        "icon": "🏛️",
        "name": "Дефолт государства",
        "duration_hours": 12,
        "description": "Государственный дефолт. Кредитование остановлено, выплата дивидендов заморожена, обвал фондового рынка и гособлигаций.",
        "one_time_stock_shock": -0.30,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 0.65,
        "block_dividends": True,
        "block_new_credits": True,
        "income_multipliers": {},
        "other_income_mult": 1.0,
        "resource_multipliers": {},
        "news_headline": "🚨 ГОСУДАРСТВЕННЫЙ ДЕФОЛТ!",
        "news_body": "Выплата дивидендов временно заморожена. Новые кредиты заблокированы. Облигации обесценились на 35%. Обвал акций на 30%!",
        "end_headline": "🏦 Финансовая система восстановлена после дефолта",
        "end_body": "Разморожена выплата дивидендов, возобновлена выдача госкредитов, цены облигаций восстановлены.",
    },
    "energy_crisis": {
        "id": "energy_crisis",
        "icon": "⚡",
        "name": "Энергетический кризис",
        "duration_hours": 24,
        "description": "Аварии на магистральных сетях. Электроэнергия в дефиците, энергетики получают сверхприбыли, все остальные заводы несут издержки.",
        "one_time_stock_shock": 0.0,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "power_engineer": 1.30,
        },
        "other_income_mult": 0.90,
        "resource_multipliers": {
            "energy": 1.50,
            "grid_quota": 1.50,
        },
        "news_headline": "⚡ Авария на магистральных электросетях!",
        "news_body": "Цены на электричество подскочили на +50%! Доходы энергетиков выросли на +30%, все остальные предприятия теряют 10% дохода.",
        "end_headline": "💡 Энергоснабжение полностью восстановлено",
        "end_body": "Магистральные сети отремонтированы. Тарифы на электроэнергию и доходы производств нормализованы.",
    },
    "fuel_crisis": {
        "id": "fuel_crisis",
        "icon": "⛽",
        "name": "Топливный коллапс",
        "duration_hours": 24,
        "description": "Остановка ключевых НПЗ. Дефицит дизеля и бензина парализует перевозки и бьет по агросектору и стройкам.",
        "one_time_stock_shock": 0.0,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "oilman": 1.30,
            "logistics": 0.70,
            "agrarian": 0.80,
            "construction": 0.80,
        },
        "other_income_mult": 0.85,
        "resource_multipliers": {
            "fuel_diesel": 1.50,
            "gasoline": 1.50,
            "jet_fuel": 1.50,
            "oil_crude": 1.50,
            "gas_natural": 1.50,
            "synthetic_fuel": 1.50,
            "cryogenic_fuel": 1.50,
        },
        "news_headline": "⛽ Остановка НПЗ: Топливный коллапс!",
        "news_body": "Цены на топливо взлетели на +50%! Все предприятия несут издержки (-15% дохода). Логистика теряет 30%, аграрии и стройка по 20%.",
        "end_headline": "⛽ Топливный кризис преодолён",
        "end_body": "НПЗ возобновили отгрузку. Цены на топливо и логистические расходы вернулись в норму.",
    },
    "water_shortage": {
        "id": "water_shortage",
        "icon": "💧",
        "name": "Водный дефицит",
        "duration_hours": 24,
        "description": "Засуха и обмеление водохранилищ. Вода дорожает, сельское хозяйство и химпром терпят рекордные убытки.",
        "one_time_stock_shock": 0.0,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "water": 1.35,
            "agrarian": 0.65,
            "chemist": 0.80,
            "metallurgist": 0.80,
        },
        "other_income_mult": 0.90,
        "resource_multipliers": {
            "water": 1.60,
            "clean_water": 1.60,
            "ultrapure_water": 1.60,
        },
        "news_headline": "💧 Рекордная засуха: острый дефицит воды!",
        "news_body": "Тарифы на воду взлетели на +60%! Все предприятия теряют 10% дохода от водного дефицита. Сельское хозяйство теряет 35%, химия и металлургия по 20%.",
        "end_headline": "🌧️ Уровень воды в водохранилищах восстановлен",
        "end_body": "Ограничения на водопользование сняты. Цены на воду и доходы производств нормализованы.",
    },
    "logistics_disruption": {
        "id": "logistics_disruption",
        "icon": "🚚",
        "name": "Сбой логистики",
        "duration_hours": 24,
        "description": "Заторы на путях и дефицит фур. Перевозки подорожали, доставка сырья задерживается и обходится дороже.",
        "one_time_stock_shock": 0.0,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "logistics": 1.25,
        },
        "other_income_mult": 0.85,
        "resource_multipliers": {
            "logistics_capacity": 1.50,
            "grain": 1.15,
            "bio_raw": 1.15,
            "wood_raw": 1.15,
            "coal": 1.15,
            "iron_ore": 1.15,
            "bauxite": 1.15,
            "minerals": 1.15,
            "oil_crude": 1.15,
            "gas_natural": 1.15,
            "copper_ore": 1.15,
        },
        "news_headline": "🚚 Транспортный паралич: сбой логистики!",
        "news_body": "Стоимость перевозок выросла на +50%, сырье подорожало на +15%! Все предприятия теряют 15% дохода из-за срыва логистических цепочек.",
        "end_headline": "🚛 Движение по транспортным артериям открыто",
        "end_body": "Заторы устранены, тарифы на логистику и цены сырья вернулись к стандарту.",
    },
    "state_construction": {
        "id": "state_construction",
        "icon": "🏗️",
        "name": "Госстройка века",
        "duration_hours": 48,
        "description": "Государство запустило масштабные инфраструктурные стройки. Спрос на стройматериалы, металл и электричество взлетел.",
        "one_time_stock_shock": 0.0,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "construction": 1.35,
            "metallurgist": 1.20,
            "power_engineer": 1.10,
            "miner": 1.10,
        },
        "other_income_mult": 1.0,
        "resource_multipliers": {
            "brick": 1.15,
            "cement": 1.15,
            "concrete": 1.15,
            "rolled_metal": 1.15,
            "steel": 1.15,
            "metal_structures": 1.15,
            "construction_capacity": 1.15,
        },
        "news_headline": "🏗️ Старт масштабной государственной стройки!",
        "news_body": "Взрывной спрос на стройматериалы (+15% к цене). Доходы строителей +35%, металлургов +20%, энергетиков и горняков +10%!",
        "end_headline": "🏢 Основной этап госстройки завершён",
        "end_body": "Госзаказ закрыт, спрос и цены на стройматериалы вернулись на рыночные уровни.",
    },
    "commodity_boom": {
        "id": "commodity_boom",
        "icon": "💎",
        "name": "Сырьевой бум",
        "duration_hours": 24,
        "description": "Взрывной мировой спрос на полезные ископаемые. Добыча на подъеме, перерабатывающие и строительные компании переплачивают за сырье.",
        "one_time_stock_shock": 0.0,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "miner": 1.30,
            "metallurgist": 1.20,
            "oilman": 1.20,
            "construction": 0.90,
            "technoprom": 0.90,
        },
        "other_income_mult": 1.0,
        "resource_multipliers": {
            "iron_ore": 1.25,
            "coal": 1.25,
            "bauxite": 1.25,
            "minerals": 1.25,
            "copper_ore": 1.25,
            "nickel_concentrate": 1.25,
            "rare_earths": 1.25,
            "lithium_raw": 1.25,
            "cobalt_raw": 1.25,
            "oil_crude": 1.25,
            "gas_natural": 1.25,
            "gold_ore": 1.25,
            "silver_ore": 1.25,
        },
        "news_headline": "💎 Мировой сырьевой бум!",
        "news_body": "Цены на добываемое сырье взлетели на +25%. Доходы горняков +30%, металлургов +20%, нефтяников +20%. Стройка и IT теряют по 10%.",
        "end_headline": "📉 Сырьевой рынок стабилизировался",
        "end_body": "Ажиотаж на первичное сырье спал, маржинальность отраслей вернулась к базовым значениям.",
    },
    "tech_deficit": {
        "id": "tech_deficit",
        "icon": "💾",
        "name": "Дефицит микрочипов",
        "duration_hours": 24,
        "description": "Глобальный сбой поставок полупроводников. Электроника в дефиците, хайтек-компании взвинчивают маржу, модернизация остальных сфер дорожает.",
        "one_time_stock_shock": 0.0,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "technoprom": 1.30,
            "power_engineer": 0.80,
            "logistics": 0.80,
            "chemist": 0.80,
        },
        "other_income_mult": 0.85,
        "resource_multipliers": {
            "components": 1.60,
            "electronics": 1.60,
            "servers": 1.60,
            "ai_accelerator": 1.60,
            "quantum_modules": 1.60,
        },
        "news_headline": "💾 Глобальный кризис полупроводников!",
        "news_body": "Цены на чипы и электронику взлетели на +60%! Все предприятия теряют 15% дохода от нехватки компонентов. Энергетика, логистика и химия теряют по 20%.",
        "end_headline": "🔬 Фабрики чипов восстановили объемы производства",
        "end_body": "Дефицит компонентов ликвидирован, цены на вычислительные модули нормализованы.",
    },
    "bad_harvest": {
        "id": "bad_harvest",
        "icon": "🌾",
        "name": "Неурожай",
        "duration_hours": 24,
        "description": "Засуха и вредители уничтожили посевы. Цены на продовольствие взлетают, агрохолдинги считают убытки.",
        "one_time_stock_shock": 0.0,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "agrarian": 0.60,
            "logistics": 1.15,
        },
        "other_income_mult": 0.85,
        "resource_multipliers": {
            "grain": 1.40,
            "bio_raw": 1.30,
            "sugar_raw": 1.40,
            "flour": 1.40,
            "food": 1.40,
            "meat": 1.40,
            "milk": 1.40,
            "feed": 1.40,
            "fresh_food": 1.40,
            "dairy_goods": 1.40,
        },
        "news_headline": "🌾 Масштабный неурожай в аграрном секторе!",
        "news_body": "Цены на зерно и продукты подскочили на +40%! Все предприятия теряют 15% дохода от продовольственного кризиса. Аграрный сектор теряет 40% доходов.",
        "end_headline": "🍞 Продовольственный рынок насыщен",
        "end_body": "Поставки зерна и продовольствия восполнены из резервов. Цены на продукты вернулись в норму.",
    },
    "deforestation_ban": {
        "id": "deforestation_ban",
        "icon": "🌲",
        "name": "Запрет на вырубку леса",
        "duration_hours": 24,
        "description": "Экологический мораторий на вырубку. Кругляк и пиломатериалы в дефиците, лесопилки простаивают, стройки тормозят.",
        "one_time_stock_shock": 0.0,
        "credit_rate_delta": 0.0,
        "bond_price_mult": 1.0,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {
            "forester": 0.75,
            "construction": 0.75,
            "chemist": 0.85,
        },
        "other_income_mult": 0.90,
        "resource_multipliers": {
            "wood_raw": 1.50,
            "lumber": 1.50,
            "cellulose": 1.50,
            "composite": 1.50,
            "cardboard": 1.50,
            "paper": 1.50,
            "engineered_wood": 1.50,
        },
        "news_headline": "🌲 Введён жесткий экологический мораторий на вырубку леса!",
        "news_body": "Древесина и пиломатериалы подорожали на +50%! Все предприятия теряют 10% дохода — дефицит материалов бьёт по всей экономике. Лесозаготовка -25%, стройка и химия -25%. В этот раз нет победителей — запасы исчерпаны у всех.",
        "end_headline": "🪵 Экологический мораторий на вырубку снят",
        "end_body": "Выделены новые квоты лесного фонда. Цены на древесину и пиломатериалы нормализованы.",
    },
    "hyperinflation": {
        "id": "hyperinflation",
        "icon": "💸",
        "name": "Гиперинфляция",
        "duration_hours": 24,
        "description": "Неконтролируемая эмиссия и обвал покупательской способности. Цены на базовые ресурсы взлетают, реальные доходы всех предприятий падают, кредитные ставки зашкаливают.",
        "one_time_stock_shock": -0.15,
        "credit_rate_delta": 0.15,
        "bond_price_mult": 0.85,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {},
        "other_income_mult": 0.75,
        "resource_multipliers": {
            "fuel_diesel": 1.40,
            "gasoline": 1.40,
            "energy": 1.40,
            "steel": 1.40,
            "food": 1.40,
            "grain": 1.40,
        },
        "news_headline": "💸 В экономике началась гиперинфляция!",
        "news_body": "Ключевые ресурсы подорожали на +40%, реальные доходы всех предприятий упали на 25%, кредитная ставка выросла на +15%!",
        "end_headline": "📉 Гиперинфляция подавлена",
        "end_body": "Монетарная политика стабилизирована. Цены на сырье и доходность предприятий вернулись в норму.",
    },
    "national_sanctions": {
        "id": "national_sanctions",
        "icon": "🚫",
        "name": "Внешнеторговые санкции",
        "duration_hours": 24,
        "description": "Международное торговое эмбарго и санкции. Налог на прибыль повышен с 13% до 23%! Поставки нарушены, экспорт и импорт заблокированы, доходы всех отраслей просели на 20%, фондовый рынок в крутом пике.",
        "one_time_stock_shock": -0.20,
        "credit_rate_delta": 0.05,
        "tax_rate_delta": 0.10,
        "bond_price_mult": 0.80,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {},
        "other_income_mult": 0.80,
        "resource_multipliers": {
            "components": 1.50,
            "electronics": 1.50,
            "logistics_capacity": 1.40,
            "fuel_diesel": 1.30,
            "rolled_metal": 1.30,
        },
        "news_headline": "🚫 Введены жесткие внешнеторговые санкции!",
        "news_body": "Торговые пути перекрыты, налог на прибыль повышен с 13% до 23% (+10%). Все компании теряют 20% дохода, импортные компоненты подорожали на 50%, фондовый рынок рухнул на 20%.",
        "end_headline": "🤝 Торговые санкции ослаблены",
        "end_body": "Международные торговые коридоры разблокированы. Ставка налога на прибыль возвращена к базовым 13%. Логистика и доходы отраслей нормализованы.",
    },
    "infrastructure_collapse": {
        "id": "infrastructure_collapse",
        "icon": "💥",
        "name": "Техногенный коллапс сетей",
        "duration_hours": 18,
        "description": "Каскадные аварии на магистральных подстанциях, водоканалах и транспортных узлах. Налог на прибыль повышен с 13% до 18% для ликвидации последствий аварий. Производство парализовано (-30% дохода), выплата дивидендов временно заморожена.",
        "one_time_stock_shock": -0.10,
        "credit_rate_delta": 0.0,
        "tax_rate_delta": 0.05,
        "bond_price_mult": 0.90,
        "block_dividends": True,
        "block_new_credits": False,
        "income_multipliers": {},
        "other_income_mult": 0.70,
        "resource_multipliers": {
            "energy": 1.60,
            "grid_quota": 1.60,
            "water": 1.60,
            "logistics_capacity": 1.60,
        },
        "news_headline": "💥 Техногенный коллапс инфраструктуры!",
        "news_body": "Каскадные аварии парализовали инфраструктуру! Налог на прибыль экстренно повышен с 13% до 18% (+5%). Энергия, вода и логистика подорожали на +60%, доходы всех предприятий упали на 30%, дивиденды заморожены.",
        "end_headline": "🛠️ Инфраструктура полностью восстановлена",
        "end_body": "Аварийные бригады устранили повреждения сетей. Ставка налога на прибыль возвращена к 13%. Энергоснабжение и выплата дивидендов возобновлены.",
    },
    "economic_boom": {
        "id": "economic_boom",
        "icon": "🚀",
        "name": "Всеобщий экономический бум",
        "duration_hours": 24,
        "description": "Беспрецедентный экономический подъем и приток инвестиций. Доходы всех отраслей растут, кредиты становятся доступнее, котировки акций летят вверх.",
        "one_time_stock_shock": 0.15,
        "credit_rate_delta": -0.05,
        "bond_price_mult": 1.10,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {},
        "other_income_mult": 1.30,
        "resource_multipliers": {},
        "news_headline": "🚀 В стране начался мощнейший экономический бум!",
        "news_body": "Взрывной рост потребительского спроса! Доходы абсолютно всех отраслей выросли на +30%, кредиты подешевели на 5%, акции компаний подскочили на +15%!",
        "end_headline": "📈 Экономический бум перешёл в устойчивый рост",
        "end_body": "Сверхпиковая активность стабилизировалась, экономика вернулась к сбалансированному состоянию.",
    },
    "state_subsidies": {
        "id": "state_subsidies",
        "icon": "💰",
        "name": "Масштабные госдотации",
        "duration_hours": 24,
        "description": "Правительство открыло резервный фонд и запустило прямые субсидии бизнесу. Все предприятия получают дотации к выручке, базовое сырье субсидируется государством.",
        "one_time_stock_shock": 0.10,
        "credit_rate_delta": -0.03,
        "bond_price_mult": 1.05,
        "block_dividends": False,
        "block_new_credits": False,
        "income_multipliers": {},
        "other_income_mult": 1.25,
        "resource_multipliers": {
            "energy": 0.85,
            "fuel_diesel": 0.85,
            "water": 0.85,
            "logistics_capacity": 0.85,
        },
        "news_headline": "💰 Запущена программа масштабных государственных субсидий!",
        "news_body": "Государство выделяет прямые дотации бизнесу: доходы всех предприятий +25%! Базовые ресурсы и логистика подешевели на 15% за счет госсубсидий. Акции растут на +10%!",
        "end_headline": "🏛️ Программа государственных субсидий завершена",
        "end_body": "Бюджетные субсидии успешно освоены. Цены ресурсов и доходность предприятий вернулись в рыночный режим.",
    },
}

SPECIALIZATION_ALIASES = {
    "builder": "construction",
    "construction": "construction",
    "it": "technoprom",
    "technoprom": "technoprom",
    "utilities": "water",
    "water": "water",
    "oil": "oilman",
    "oilgas": "oilman",
    "oilman": "oilman",
    "energy": "power_engineer",
    "power_engineer": "power_engineer",
    "forestry": "forester",
    "forester": "forester",
    "agriculture": "agrarian",
    "agrarian": "agrarian",
    "mining": "miner",
    "miner": "miner",
    "metallurgy": "metallurgist",
    "metallurgist": "metallurgist",
    "chemistry": "chemist",
    "chemist": "chemist",
    "logistics": "logistics",
}


def get_sabotage_spec(sabotage_id: str) -> Optional[Dict[str, Any]]:
    return SABOTAGES_CATALOG.get((sabotage_id or "").strip().lower())


def normalize_specialization(spec: str) -> str:
    cleaned = (spec or "").strip().lower()
    return SPECIALIZATION_ALIASES.get(cleaned, cleaned)
