"""Rules shared by state credit application and approval services."""

STATE_CREDIT_INTEREST_RATE_PCT = 15.0
STATE_CREDIT_DAILY_RATE = STATE_CREDIT_INTEREST_RATE_PCT / 100
STATE_CREDIT_MAX_TERM_DAYS = 5
STATE_CREDIT_MAX_NAV_PCT = 50.0
STATE_CREDIT_OPEN_STATUSES = ("PENDING", "ACTIVE", "DEFAULTED")

__all__ = [
    "STATE_CREDIT_INTEREST_RATE_PCT",
    "STATE_CREDIT_DAILY_RATE",
    "STATE_CREDIT_MAX_TERM_DAYS",
    "STATE_CREDIT_MAX_NAV_PCT",
    "STATE_CREDIT_OPEN_STATUSES",
]
